const BLOGS = [
  {
    id: 91,
    title: "Masterclass de l'entretien printanier : protocoles CVAC à faire soi-même vs entretien professionnel dans les régions 613 et 514",
    publication: "Aura ClimatPro",
    date: "June 24, 2026",
    dateISO: "2026-06-24",
    wordCount: 1600,
    readTime: 8,
    url: "https://auraclimatpro.com/masterclass-de-lentretien-printanier-protocoles-cvac-a-faire-soi-meme-vs-entretien-professionnel-dans-les-regions-613-et-514/",
    excerpt: "Version française de la Masterclass d'entretien printanier CVAC pour les régions 613 et 514 — couvrant le yo-yo thermique de Gatineau et Ottawa (-7 °C la nuit à 19 °C le jour), les protocoles DIY (filtre MERV 13, rinçage des ailettes, nettoyage du drain au vinaigre) vs professionnels (mesure du différentiel de température, diagnostic condensateur en microfarads, détection électronique des fuites de réfrigérant), ainsi que les exigences réglementaires TSSA Ontario et RBQ/CMMTQ Québec.",
    tags: ["CVAC", "Entretien", "Ottawa", "Montréal", "Québec", "Ontario", "QAI", "Français", "Printemps", "Efficacité énergétique"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 90,
    title: "Spring Maintenance Masterclass: DIY vs. Professional HVAC Protocols for the 613 and 514",
    publication: "Aura ClimatPro",
    date: "June 23, 2026",
    dateISO: "2026-06-23",
    wordCount: 1600,
    readTime: 8,
    url: "https://auraclimatpro.com/spring-maintenance-masterclass-diy-vs-professional-hvac-protocols-for-the-613-and-514/",
    excerpt: "Ottawa and Montreal's spring 'thermal yo-yo' (-7°C nights to 19°C days) is the top cause of HVAC mechanical fatigue — and the pollen surge from Birch, Maple, and Oak is peaking earlier every year. Covers the full DIY protocol (MERV 13 filter audits, condenser fin rinse, vinegar drain flush) vs. professional protocols (temperature split measurement, capacitor microfarad testing, electronic refrigerant leak detection), TSSA Ontario and RBQ/CMMTQ Quebec licensing rules, and how neglected systems lose 5% efficiency annually adding up to $5,000–$15,000 in premature replacement costs.",
    tags: ["HVAC", "Maintenance", "Ottawa", "Montreal", "Quebec", "Ontario", "IAQ", "DIY", "Spring", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 89,
    title: "Grass Allergies vs. IAQ: Turning Your Winnipeg Home into a Sanctuary",
    publication: "WiserAire",
    date: "June 22, 2026",
    dateISO: "2026-06-22",
    wordCount: 1700,
    readTime: 9,
    url: "https://wiseraire.com/grass-allergies-vs-iaq-turning-your-winnipeg-home-into-a-sanctuary/",
    excerpt: "Winnipeg's 'pollen collision' — trees in May, grasses in June, peak counts in July — makes indoor air up to 5× more polluted than outside as airtight homes trap allergens in ductwork. Covers the GeneralAire MAC 1400 media filter for 1–3 micron grass pollen, the 5-stage AMHP-250-UPD clinical purifier (HEPA + UVC + PCO), the 30–40% humidity sweet spot for dust mite suppression, ERV fresh-air solutions, and Manitoba Hydro's HEEL loan (up to $20,000) and Energy Finance Plan (up to $5,000) for IAQ equipment.",
    tags: ["IAQ", "Allergies", "Winnipeg", "Manitoba", "Air Quality", "HVAC", "HEPA", "Rebates", "Humidity", "ERV"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 88,
    title: "The Hydronics Advantage: Why Ontario Homeowners are Choosing Boiler and Combi-System Upgrades in 2026",
    publication: "Constant Home Comfort",
    date: "June 19, 2026",
    dateISO: "2026-06-19",
    wordCount: 1800,
    readTime: 9,
    url: "https://www.constanthomecomfort.com/news-detail?pid=3&slug=the-hydronics-advantage-why-ontario-homeowners-are-choosing-boiler-and-combi-system-upgrades-in-2026",
    excerpt: "Water carries heat 3,500× more efficiently than air — and in 2026, Ontario homeowners from Markham to Kanata are switching from forced-air furnaces to hydronic boilers and combi systems to eliminate duct losses (up to 30%), dry air, and hot/cold spots. Covers Navien NPE-2 vs. Rinnai SENSEI RX for Ontario's -30°C winters, combi vs. solo boiler decisions for high-demand households, HRSP rebates stacking to $10,000+, hybrid hydronic-heat pump setups with $7,500 incentives, and 2026 Ontario Fire Code CO alarm compliance requirements.",
    tags: ["HVAC", "Boiler", "Hydronics", "Ontario", "Rebates", "HRSP", "Navien", "Rinnai", "Energy Efficiency", "Combi System"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 87,
    title: "Beating the 2026 Vancouver Heatwave: A Homeowner's Guide to the Pre-Summer Rush and Labor Shortages",
    publication: "AireEnergy",
    date: "June 18, 2026",
    dateISO: "2026-06-18",
    wordCount: 1700,
    readTime: 9,
    url: "https://aireenergy.com/beating-the-2026-vancouver-heatwave-a-homeowners-guide-to-the-pre-summer-rush-and-labor-shortages/",
    excerpt: "2026 is on track to be one of Canada's hottest years on record — but the real crisis is 22% of HVAC technicians nearing retirement, pushing GVA heatwave wait times to 5–14 business days and emergency repair costs up 10–20%. Covers the R-410A to R-32/R-454B A2L refrigerant transition, CleanBC rebates up to $16,000, and neighborhood-specific guidance for Surrey, Langley, Burnaby, Coquitlam, Delta, and Squamish — from heritage home ductless retrofits in Fort Langley to salt-air corrosion coatings in Tsawwassen.",
    tags: ["HVAC", "Heat Pump", "Vancouver", "British Columbia", "CleanBC", "Rebates", "Refrigerant", "Labor Shortage", "GVA", "Summer"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 86,
    title: "The \"Repair-First\" Economy: Why a $500 Fix Might Be Better Than a $15,000 Replacement",
    publication: "ComfiTrust",
    date: "June 17, 2026",
    dateISO: "2026-06-17",
    wordCount: 1600,
    readTime: 8,
    url: "https://comfitrust.com/the-repair-first-economy-why-a-500-fix-might-be-better-than-a-15000-replacement/",
    excerpt: "Over 67% of homeowners now prefer repair over replacement — and in Boston, where new installs mean mechanical permits, 19th-century staircases, and $12,000–$15,000 quotes driven by A2L refrigerant regulations, the 'Repair-First' economy makes pure financial sense. Covers the $5,000 Rule and 50% Rule for deciding when to fix vs. replace, the five '$500 heroes' (capacitor, contactor, flame sensor, condensate drain), Mass Save's 0% HEAT Loan up to $25,000, and when a cracked heat exchanger makes repair a genuine safety hazard.",
    tags: ["HVAC", "Repair", "Boston", "Mass Save", "Cost Savings", "Maintenance", "Heat Pump", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 85,
    title: "Heat Pump vs. AC: Why the $7,500 Rebate Wins",
    publication: "Constant Home Comfort",
    date: "June 16, 2026",
    dateISO: "2026-06-16",
    wordCount: 1800,
    readTime: 9,
    url: "https://www.constanthomecomfort.com/news-detail?pid=2&slug=heat-pump-vs-ac-why-the-7500-rebate-wins",
    excerpt: "Ontario's Home Renovation Savings Program has flipped the HVAC cost equation: cold-climate heat pumps now qualify for up to $7,500 in rebates, making them cheaper net than a standard AC — which comes with zero rebates and only solves cooling. Covers rebate tiers by fuel type (electric/$7,500, oil-propane/$7,500 stackable with federal OHPA, gas/$2,000), the 2026 no-audit path, carbon tax impact at $110/tonne rising to $170 by 2030, regional install differences from Ottawa's -30°C winters to Hamilton's lake-effect humidity, and variable-speed inverter efficiency from 200–400% COP.",
    tags: ["HVAC", "Heat Pump", "Ontario", "Rebates", "HRSP", "Energy Efficiency", "Carbon Tax", "ClimateControl", "Inverter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 84,
    title: "The \"Boston Soup\": Why Your AC is Failing You and How Inverter Tech Fixes It",
    publication: "ComfiTrust",
    date: "June 15, 2026",
    dateISO: "2026-06-15",
    wordCount: 1500,
    readTime: 8,
    url: "https://comfitrust.com/the-boston-soup-why-your-ac-is-failing-you-and-how-inverter-tech-fixes-it/",
    excerpt: "Boston's 82°F summer days feel miserable because the real enemy is 72% humidity — and traditional single-stage AC units are 'light switches' that short-cycle before they can pull moisture out of the air. Inverter systems from Mitsubishi and Gree act as dimmer switches, running at low continuous speeds to actually dehumidify 100-year-old triple-deckers and brick row houses. Covers Mitsubishi's 3D i-see Sensor and Dry Mode, Gree Airy's target humidity control and X-Fan mold prevention, Mass Save's $8,500 rebate and 0% HEAT Loan up to $25,000, and R-410A refrigerant ban effective 2026.",
    tags: ["HVAC", "AC", "Inverter", "Boston", "Humidity", "Mitsubishi", "Gree", "Mass Save", "Rebates", "IAQ"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 83,
    title: "The Smart Home Evolution: Why Your BC Home is Finally Getting a Brain",
    publication: "AireEnergy",
    date: "June 12, 2026",
    dateISO: "2026-06-12",
    wordCount: 2200,
    readTime: 11,
    url: "https://aireenergy.com/the-smart-home-evolution-why-your-bc-home-is-finally-getting-a-brain/",
    excerpt: "The 'smart home' has evolved from a Jetsons fantasy to a BC reality — driven by the Matter interoperability protocol, AI-powered predictive maintenance, and cold-climate heat pumps hitting 300–400% efficiency. Covers GVA microclimates from Squamish moisture battles to Burnaby heat islands, CleanBC rebates up to $16,000, the Energy Savings Program covering up to 95% of costs for income-qualified families, and how smart zoning and IAQ sensors are reshaping comfort across Surrey, Langley, and Port Coquitlam.",
    tags: ["HVAC", "Smart Home", "British Columbia", "Heat Pump", "CleanBC", "Rebates", "Energy Efficiency", "GVA", "AI"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 1,
    title: "Technoeconomic Analysis: The 2026 Shift to Smart HVAC Standards in Greater Boston",
    publication: "ComfiTrust",
    date: "January 5, 2026",
    dateISO: "2026-01-05",
    wordCount: 1300,
    readTime: 7,
    url: "https://comfitrust.com/technoeconomic-analysis-the-2026-shift-to-smart-hvac-standards-in-greater-boston/",
    excerpt: "As of 2026, Boston's HVAC sector has crossed the tipping point where system intelligence replaces mechanical reliability as the primary quality metric — driven by BERDO emissions mandates, R-410A refrigerant phase-outs, and AI-powered predictive comfort systems reshaping how Greater Boston homes manage climate and energy.",
    tags: ["HVAC", "Smart Home", "Energy Efficiency", "Boston", "AI", "Real Estate"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 2,
    title: "The Emergency 'No-Heat' Playbook: What to Do During a Polar Vortex",
    publication: "ComfiTrust",
    date: "January 8, 2026",
    dateISO: "2026-01-08",
    wordCount: 1000,
    readTime: 5,
    url: "https://comfitrust.com/the-emergency-no-heat-playbook-what-to-do-during-a-polar-vortex/",
    excerpt: "When a Polar Vortex hits Greater Boston, it's a brutal test of your home's high-efficiency heating system. This step-by-step emergency playbook covers safety triage, PVC vent checks, error code decoding for Gree, Mitsubishi, and Bosch systems, and how to protect your pipes — so you're never left in the cold at 2 AM.",
    tags: ["HVAC", "Emergency", "Heat Pump", "Boston", "Winter", "Troubleshooting"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 3,
    title: "Massachusetts Heat Pump Reality Check: Do They Really Work at -15°F?",
    publication: "ComfiTrust",
    date: "January 12, 2026",
    dateISO: "2026-01-12",
    wordCount: 1000,
    readTime: 5,
    url: "https://comfitrust.com/massachusetts-heat-pump-reality-check-do-they-really-work-at-15f/",
    excerpt: "A technical reality check on air-source heat pumps in New England winters — examining COP ratings across temperature ranges, EVI and Flash Injection technology, brand comparisons across Mitsubishi, Bosch, and Daikin, and Massachusetts-specific rebates and the No-Cost Heat Pump Program.",
    tags: ["HVAC", "Heat Pump", "Massachusetts", "Winter", "Rebates", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 4,
    title: "Nova Scotia Rebate Update: The 2026 Guide",
    publication: "Auxaire",
    date: "January 13, 2026",
    dateISO: "2026-01-13",
    wordCount: 1600,
    readTime: 8,
    url: "https://auxaire.com/2026/01/13/nova-scotia-rebate-update-the-2026-guide/",
    excerpt: "Nova Scotia homeowners can stack up to $30,000 in 2026 rebates for switching from oil to heat pumps — but major programs are expected to deplete early. This guide covers OHPA grants, income-based top-ups, Efficiency NS home assessments, supplemental insulation rebates, and 0% PACE financing options.",
    tags: ["Rebates", "Nova Scotia", "Heat Pump", "Energy Efficiency", "HVAC", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 5,
    title: "The \"Burning Plastic\" Smell: Is Your Furnace Safe?",
    publication: "WiserAire",
    date: "January 14, 2026",
    dateISO: "2026-01-14",
    wordCount: 1600,
    readTime: 8,
    url: "https://wiseraire.com/the-burning-plastic-smell-is-your-furnace-safe/",
    excerpt: "That burning plastic smell from your furnace could be dust — or a failing blower motor, electrical arcing, or a cracked heat exchanger leaking carbon monoxide. This Winnipeg-focused guide walks through the three main causes, emergency shutdown steps, and when to call for 24/7 repair.",
    tags: ["HVAC", "Furnace", "Safety", "Winnipeg", "Carbon Monoxide", "Troubleshooting"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 6,
    title: "Is Your Heat Pump Ready for -30°C? A Maritime Survival Guide",
    publication: "Auxaire",
    date: "January 9, 2026",
    dateISO: "2026-01-09",
    wordCount: 1300,
    readTime: 7,
    url: "https://auxaire.com/2026/01/09/is-your-heat-pump-ready-for-30c-a-maritime-survival-guide/",
    excerpt: "Modern cold-climate heat pumps can hold the line at -30°C — but only if they're properly sized, coated for coastal salt air, and backed by the right dual-fuel strategy. This Maritime survival guide covers Enhanced Vapor Injection technology, anti-corrosion coatings, frost management, and 2026 rebate programs offering up to $30,000 in Nova Scotia.",
    tags: ["HVAC", "Heat Pump", "Nova Scotia", "Winter", "Rebates", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 7,
    title: "Navigating the 2026 Mass Save Rebate Reductions: What You Need to Know NOW",
    publication: "ComfiTrust",
    date: "January 15, 2026",
    dateISO: "2026-01-15",
    wordCount: 1500,
    readTime: 8,
    url: "https://comfitrust.com/navigating-the-2026-mass-save-rebate-reductions-what-you-need-to-know-now/",
    excerpt: "Massachusetts homeowners face a \"triple hit\" to heat pump budgets in 2026 as Mass Save slashes maximum rebates from $10,000 to $8,500, new tonnage-based calculations and refrigerant compliance rules tighten eligibility, and federal Section 25C tax credits expire — with a breakdown of what to do before the cuts take full effect.",
    tags: ["HVAC", "Heat Pump", "Massachusetts", "Rebates", "Energy Efficiency", "Mass Save"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 8,
    title: "Manitoba Hydro Bills Too High? 5 Ways to Optimize Your Furnace Today",
    publication: "WiserAire",
    date: "January 16, 2026",
    dateISO: "2026-01-16",
    wordCount: 1800,
    readTime: 9,
    url: "https://wiseraire.com/manitoba-hydro-bills-too-high-5-ways-to-optimize-your-furnace-today/",
    excerpt: "Five practical strategies for cutting Manitoba Hydro bills through furnace optimization — from filter swaps and duct sealing to smart thermostats and intelligent monitoring — with cost estimates and expected savings for each upgrade.",
    tags: ["HVAC", "Furnace", "Energy Efficiency", "Winnipeg", "Manitoba", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 9,
    title: "Why Your Boston Home Has Hot and Cold Spots (and How to Fix Them)",
    publication: "ComfiTrust",
    date: "January 20, 2026",
    dateISO: "2026-01-20",
    wordCount: 1400,
    readTime: 7,
    url: "https://comfitrust.com/why-your-boston-home-has-hot-and-cold-spots-and-how-to-fix-them/",
    excerpt: "Boston homes battle temperature imbalances caused by the stack effect, aging ductwork, and urban heat islands — this guide covers professional air balancing, zoning systems, and ductless mini-splits as targeted fixes, with Mass Save rebates that can offset upgrade costs.",
    tags: ["HVAC", "Boston", "Heat Pump", "Energy Efficiency", "Mass Save", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 10,
    title: "Where Should You Actually Put CO Detectors in a Split-Level Home?",
    publication: "WiserAire",
    date: "January 22, 2026",
    dateISO: "2026-01-22",
    wordCount: 1000,
    readTime: 5,
    url: "https://wiseraire.com/where-should-you-actually-put-co-detectors-in-a-split-level-home/",
    excerpt: "CO doesn't sink or rise — it follows airflow, which makes split-level homes especially tricky. This guide covers the exact placement rules for bedroom doors, garage entries, and mechanical spaces, plus the common installation mistakes that leave dangerous blind spots.",
    tags: ["Safety", "Carbon Monoxide", "HVAC", "Furnace", "Winnipeg", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 11,
    title: "Why Is My Furnace Blowing Cold Air?",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/why-is-my-furnace-blowing-cold-air/",
    excerpt: "A furnace blowing cold air isn't always a crisis — seven common culprits from thermostat mode to dirty filters can be ruled out before calling a tech. This Montreal-focused guide walks through each cause and the DIY fix or escalation threshold for each.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 12,
    title: "Pourquoi mon fournaise souffle-t-elle de l'air froid?",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1400,
    readTime: 7,
    url: "https://auraclimatpro.com/pourquoi-mon-fournaise-souffle-t-elle-de-lair-froid/",
    excerpt: "Une fournaise qui souffle de l'air froid n'est pas toujours en panne — sept causes courantes, du réglage du thermostat au filtre encrassé, peuvent être éliminées avant d'appeler un technicien. Guide de dépannage pour propriétaires montréalais.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "French", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 13,
    title: "Stop Cringing at Your Energy Bill: 10 Ways to Stay Warm for Less",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1000,
    readTime: 5,
    url: "https://auraclimatpro.com/stop-cringing-at-your-energy-bill-10-ways-to-stay-warm-for-less/",
    excerpt: "Ten budget-friendly strategies to cut winter heating costs without sacrificing comfort — from weatherstripping and programmable thermostats to HVAC maintenance and smart home upgrades, with practical thresholds for when a professional tune-up pays for itself.",
    tags: ["Energy Efficiency", "HVAC", "Home Improvement", "Montreal", "Smart Home", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 14,
    title: "Arrêtez de grimacer devant votre facture d'énergie: 10 façons de rester au chaud à moindre coût",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/arretez-de-grimacer-devant-votre-facture-denergie-10-facons-de-rester-au-chaud-a-moindre-cout/",
    excerpt: "Dix stratégies pratiques pour réduire les factures de chauffage hivernal — calfeutrage des fuites, thermostats intelligents et optimisation de la ventilation — pour rester au chaud à Montréal sans sacrifier le budget.",
    tags: ["Energy Efficiency", "HVAC", "Home Improvement", "Montreal", "French", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 15,
    title: "Boiler vs. Furnace: The Best Heating Options for Historic Beacon Hill Brownstones",
    publication: "ComfiTrust",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1000,
    readTime: 5,
    url: "https://comfitrust.com/boiler-vs-furnace-the-best-heating-options-for-historic-beacon-hill-brownstones/",
    excerpt: "Beacon Hill's solid masonry brownstones make ductwork nearly impossible — this breakdown explains why boilers outperform furnaces in historic homes, how hybrid heat pump systems fit the preservation constraints, and which Mass Save rebates apply in 2026.",
    tags: ["HVAC", "Boston", "Heat Pump", "Rebates", "Mass Save", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 16,
    title: "Why January is the Best Time for a New HVAC Quote (And Why Waiting Until Spring Could Cost You)",
    publication: "Auxaire",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1300,
    readTime: 7,
    url: "https://auxaire.com/2026/01/23/why-january-is-the-best-time-for-a-new-hvac-quote-and-why-waiting-until-spring-could-cost-you/",
    excerpt: "January is the quiet before the spring rush — and that window means better pricing, faster installs, and full access to OHPA rebates before funds run dry. This guide breaks down why the refrigerant transition to R-454B and pre-season manufacturer pricing make right now the best time to get an HVAC quote in the Maritimes.",
    tags: ["HVAC", "Rebates", "Nova Scotia", "Heat Pump", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 17,
    title: "Understanding the \"Code Error\" Flashing on Your Furnace: A Homeowner's Guide to Decoding the Blink",
    publication: "WiserAire",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1500,
    readTime: 8,
    url: "https://wiseraire.com/understanding-the-code-error-flashing-on-your-furnace-a-homeowners-guide-to-decoding-the-blink/",
    excerpt: "That blinking light on your furnace isn't random — it's a diagnostic code pointing to a specific fault like a blocked exhaust vent, high limit switch trip, or ignition failure. This Winnipeg homeowner's guide decodes the most common blink patterns and tells you which ones need a tech immediately.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Winnipeg", "Safety", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 18,
    title: "Furnace vs. Heat Pump: Which Is Better for Canadian Winters?",
    publication: "AuraClimatpro",
    date: "January 28, 2026",
    dateISO: "2026-01-28",
    wordCount: 1100,
    readTime: 6,
    url: "https://auraclimatpro.com/furnace-vs-heat-pump-which-is-better-for-canadian-winters/",
    excerpt: "Modern cold-climate heat pumps have made the furnace vs. heat pump debate more nuanced than ever. This guide explains why dual-energy systems — pairing an electric heat pump with a gas furnace backup — are the smart choice for Quebec homeowners looking to leverage low hydro rates without sacrificing winter comfort.",
    tags: ["HVAC", "Heat Pump", "Furnace", "Montreal", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 19,
    title: "Fournaise vs Thermopompe: Quel est le meilleur choix pour l'hiver québécois?",
    publication: "AuraClimatpro",
    date: "January 28, 2026",
    dateISO: "2026-01-28",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/fournaise-vs-thermopompe-quel-est-le-meilleur-choix-pour-lhiver-quebecois/",
    excerpt: "La technologie moderne des thermopompes pour climat froid a changé la donne — cet article compare fournaise et thermopompe pour les hivers québécois et explique pourquoi les systèmes biénergie, combinant les deux, permettent de profiter des bas tarifs d'Hydro-Québec sans compromettre le confort.",
    tags: ["HVAC", "Heat Pump", "Furnace", "Montreal", "French", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 20,
    title: "When Should You Replace Your Furnace? 5 Clear Warning Signs",
    publication: "AuraClimatpro",
    date: "February 2, 2026",
    dateISO: "2026-02-02",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/when-should-you-replace-your-furnace-5-clear-warning-signs/",
    excerpt: "Five clear signs your furnace needs replacing — age over 15 years, rising utility bills, unusual noises, uneven heating, and frequent repairs — with Montreal-specific guidance on professional installation, heritage home considerations, and how 2026 rebates make upgrading more affordable than ever.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 21,
    title: "Quand devriez-vous remplacer votre fournaise? 5 signes qui ne trompent pas",
    publication: "AuraClimatpro",
    date: "January 30, 2026",
    dateISO: "2026-01-30",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/quand-devriez-vous-remplacer-votre-fournaise-5-signes-qui-ne-trompent-pas/",
    excerpt: "Votre fournaise envoie souvent des signaux d'alarme bien avant de lâcher — âge de 15 ans et plus, factures en hausse inexpliquée, bruits inhabituels, chaleur inégale, et réparations répétées sont les cinq signes qui indiquent qu'un remplacement est plus économique qu'une réparation. Guide montréalais avec conseils d'installation professionnelle.",
    tags: ["HVAC", "Furnace", "Montreal", "French", "Troubleshooting", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 22,
    title: "The Hidden Threat: Why Your Boston Home Needs a Winter Furnace Check-up Right Now",
    publication: "ComfiTrust",
    date: "February 3, 2026",
    dateISO: "2026-02-03",
    wordCount: 1100,
    readTime: 6,
    url: "https://comfitrust.com/the-hidden-threat-why-your-boston-home-needs-a-winter-furnace-check-up-right-now/",
    excerpt: "Carbon monoxide is undetectable by human senses and mimics flu symptoms — making winter the most dangerous season for Boston homeowners with aging furnaces. This guide covers snow-blocked vents, heat exchanger cracks, Massachusetts Nicole's Law detector requirements, and why a professional combustion analysis beats relying on alarms alone.",
    tags: ["HVAC", "Furnace", "Safety", "Boston", "Carbon Monoxide", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 23,
    title: "The Manitoba Hydro Home Energy Efficiency Loan: A Step-by-Step Guide",
    publication: "WiserAire",
    date: "February 4, 2026",
    dateISO: "2026-02-04",
    wordCount: 1100,
    readTime: 6,
    url: "https://wiseraire.com/the-manitoba-hydro-home-energy-efficiency-loan-a-step-by-step-guide/",
    excerpt: "Manitoba Hydro's 2026 energy efficiency loan offers up to $12,500 (or $20,000 for solar/geothermal) at a fixed 6.20% rate with no down payment — this step-by-step guide covers qualifying upgrades, the five-step application sequence, and the most common denial reasons to avoid.",
    tags: ["HVAC", "Rebates", "Manitoba", "Energy Efficiency", "Furnace", "Heat Pump"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 24,
    title: "Battery Storage Systems: Backup Power and Energy Savings for BC Homes",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-01",
    wordCount: 1200,
    readTime: 6,
    url: "https://aireenergy.com/battery-storage-systems-backup-power-and-energy-savings-for-bc-homes/",
    excerpt: "BC's aging grid and severe weather events are driving demand for home battery storage — this guide covers time-of-use rate optimization with BC Hydro's new pricing structure, LFP battery technology, stacking $10,000+ in solar and storage rebates before the April 2026 deadline, and how to integrate batteries with heat pumps and EV chargers.",
    tags: ["Energy Efficiency", "Solar", "Battery Storage", "British Columbia", "Rebates", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 25,
    title: "Le frisson de 2h du matin: que faire lors d'une urgence de chauffage en plein hiver?",
    publication: "AuraClimatpro",
    date: "February 6, 2026",
    dateISO: "2026-02-06",
    wordCount: 1000,
    readTime: 5,
    url: "https://auraclimatpro.com/le-frisson-de-2h-du-matin-que-faire-lors-dune-urgence-de-chauffage-en-plein-hiver/",
    excerpt: "Quand la fournaise lâche à -20°C à 2h du matin, chaque minute compte — ce guide d'urgence couvre la checklist de base, l'inspection des filtres et des conduits PVC, les mesures anti-gel pour les tuyaux, et les trois signaux (gaz, CO, fumée) qui exigent une évacuation immédiate.",
    tags: ["HVAC", "Furnace", "Emergency", "Montreal", "French", "Safety", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 26,
    title: "The 2 AM Chill: What to Do During a Mid-Winter Heating Emergency",
    publication: "AuraClimatpro",
    date: "February 9, 2026",
    dateISO: "2026-02-09",
    wordCount: 900,
    readTime: 5,
    url: "https://auraclimatpro.com/the-2-am-chill-what-to-do-during-a-mid-winter-heating-emergency/",
    excerpt: "When your furnace dies at -20°C in the middle of the night, every minute counts — this emergency guide walks through the quick-check checklist, airflow fixes, pipe-freeze prevention, and the three warning signs (gas, CO, burning smell) that mean you need to evacuate immediately.",
    tags: ["HVAC", "Furnace", "Emergency", "Montreal", "Safety", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--mint))"
  },
  {
    id: 28,
    title: "The Winter Trap: Why Your Indoor Air Quality Drops When the Temperature Plummets",
    publication: "ComfiTrust",
    date: "February 10, 2026",
    dateISO: "2026-02-10",
    wordCount: 1800,
    readTime: 9,
    url: "https://comfitrust.com/the-winter-trap-why-your-indoor-air-quality-drops-when-the-temperature-plummets/",
    excerpt: "Indoor air can be up to five times more polluted than outdoor air in winter — sealed homes, furnace dust, low humidity, and cooking particulates all compound the problem. This Boston-focused guide covers True HEPA filtration, UV-C light purification, and the 30-50% humidity \"Goldilocks Zone\" for healthier winter air.",
    tags: ["HVAC", "Air Quality", "Boston", "Health", "Furnace", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 29,
    title: "Furnace End-of-Life: Repair or Replace? (The $500 Rule)",
    publication: "WiserAire",
    date: "February 11, 2026",
    dateISO: "2026-02-11",
    wordCount: 1100,
    readTime: 6,
    url: "https://wiseraire.com/furnace-end-of-life-repair-or-replace-the-500-rule/",
    excerpt: "Three rules help Winnipeg homeowners decide between furnace repair and replacement: the $500 Rule for minor fixes, the 5000 HVAC Rule (age × repair cost), and the 50% Rule when quotes approach half the cost of a new system — plus why a cracked heat exchanger almost always tips the math toward replacement.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Winnipeg", "Home Improvement", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 30,
    title: "Turning the Vancouver Rain into ROI: Your Guide to BC Solar in 2026",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-01",
    wordCount: 1800,
    readTime: 9,
    url: "https://aireenergy.com/turning-the-vancouver-rain-into-roi-your-guide-to-bc-solar-in-2026/",
    excerpt: "Vancouver's cloudy reputation undersells its solar potential — modern PERC panels capture diffuse light effectively, and BC's 2026 rebates stack up to $10,000 before April 1st changes hit. This guide covers net metering credits, battery integration, optimal roof angles for rain self-cleaning, and financial projections showing break-even in 8–12 years.",
    tags: ["Solar", "Energy Efficiency", "British Columbia", "Rebates", "Battery Storage", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 31,
    title: "Furnace End-of-Life: Repair or Replace? (The $500 Rule)",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-15",
    wordCount: 1100,
    readTime: 6,
    url: "https://aireenergy.com/furnace-end-of-life-repair-or-replace-the-500-rule/",
    excerpt: "Vancouver homeowners weighing furnace repair vs. replacement can use three simple rules — the $500 threshold for minor fixes, the 5000 HVAC Rule (age × repair cost), and the 50% Rule — to cut through the pressure of a mid-winter breakdown. Cracked heat exchangers are the one exception that almost always mandate full replacement regardless of cost.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "British Columbia", "Home Improvement", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 32,
    title: "Votre maison étouffe-t-elle? Pourquoi la qualité de l'air est vitale cet hiver au Québec",
    publication: "AuraClimatpro",
    date: "February 18, 2026",
    dateISO: "2026-02-18",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/votre-maison-etouffe-t-elle-pourquoi-la-qualite-de-lair-est-vitale-cet-hiver-au-quebec/",
    excerpt: "Les maisons québécoises hermétiquement fermées en hiver piègent des polluants 2 à 5 fois plus concentrés qu'à l'extérieur — poussières, COV, particules virales et radon. Ce guide couvre la gestion de l'humidité (30–50%), la technologie Lennox PureAir S, et les ventilateurs à récupération de chaleur (VRC) pour respirer sainement sans gaspiller l'énergie.",
    tags: ["HVAC", "Air Quality", "Montreal", "French", "Health", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 33,
    title: "Your Home is Holding Its Breath: Why Winter Air Quality is a Health Priority",
    publication: "AuraClimatpro",
    date: "February 18, 2026",
    dateISO: "2026-02-18",
    wordCount: 1400,
    readTime: 7,
    url: "https://auraclimatpro.com/your-home-is-holding-its-breath-why-winter-air-quality-is-a-health-priority/",
    excerpt: "Sealed winter homes trap indoor air that's 2–5× more polluted than outside — accumulating dust, VOCs, airborne pathogens, and radon. This Montreal guide covers whole-home humidification (targeting 30–50%), the Lennox PureAir S system's three-layer purification, and HRV/ERV ventilation for fresh air without heat loss.",
    tags: ["HVAC", "Air Quality", "Montreal", "Health", "Winter", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 34,
    title: "À quelle fréquence devriez-vous faire l'entretien de votre fournaise? Le guide complet pour un hiver sans tracas",
    publication: "AuraClimatpro",
    date: "February 24, 2026",
    dateISO: "2026-02-24",
    wordCount: 1800,
    readTime: 9,
    url: "https://auraclimatpro.com/a-quelle-frequence-devriez-vous-faire-lentretien-de-votre-fournaise-le-guide-complet-pour-un-hiver-sans-tracas/",
    excerpt: "Les fournaises québécoises tournent 2 000 à 3 000 heures par hiver — un entretien annuel en septembre-octobre protège la garantie, évite 15% de surconsommation énergétique et détecte les fuites de monoxyde de carbone avant le grand froid. Guide complet des tâches DIY, des inspections professionnelles et des signaux d'alarme à surveiller.",
    tags: ["HVAC", "Furnace", "Montreal", "French", "Home Improvement", "Safety"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 35,
    title: "How Often Should You Service Your Furnace? A Complete Guide to Heating Reliability",
    publication: "AuraClimatpro",
    date: "February 24, 2026",
    dateISO: "2026-02-24",
    wordCount: 1300,
    readTime: 7,
    url: "https://auraclimatpro.com/how-often-should-you-service-your-furnace-a-complete-guide-to-heating-reliability/",
    excerpt: "Annual furnace servicing in late September or October protects your warranty, catches carbon monoxide risks early, and can cut energy bills — this guide draws the line between what Montreal homeowners can handle themselves (filter checks, vent clearing) and what needs a technician (combustion calibration, burner cleaning, electrical inspection).",
    tags: ["HVAC", "Furnace", "Montreal", "Home Improvement", "Safety", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 36,
    title: "Ductless Mini-Splits: Are They Really the Right Move for Your Home?",
    publication: "AuraClimatpro",
    date: "March 2, 2026",
    dateISO: "2026-03-02",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/ductless-mini-splits-are-they-really-the-right-move-for-your-home/",
    excerpt: "Ductless mini-split systems promise zoned comfort and significant energy savings — but are they the right fit for Canadian homes? This guide examines cold-climate performance, installation costs, Quebec and Ontario rebate eligibility, and how mini-splits stack up against traditional central systems for Ottawa and Gatineau homeowners.",
    tags: ["HVAC", "Heat Pump", "Mini-Split", "Energy Efficiency", "Ottawa", "Rebates", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--mint))"
  },
  {
    id: 37,
    title: "Mini-splits sans conduits: Est-ce vraiment la solution idéale pour votre foyer?",
    publication: "AuraClimatpro",
    date: "March 2, 2026",
    dateISO: "2026-03-02",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/mini-splits-sans-conduits-est-ce-vraiment-la-solution-ideale-pour-votre-foyer/",
    excerpt: "Les systèmes mini-split sans conduits promettent confort par zone et économies d'énergie — mais sont-ils le bon choix pour les maisons canadiennes? Ce guide examine les performances en climat froid, les coûts d'installation, l'admissibilité aux subventions du Québec et de l'Ontario, et la comparaison avec les systèmes centraux traditionnels pour les propriétaires d'Ottawa-Gatineau.",
    tags: ["HVAC", "Thermopompe", "Mini-Split", "Efficacité Énergétique", "Ottawa", "Subventions", "French"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 38,
    title: "Strategic Content Whitepaper: Optimizing Winter HVAC Assets for Aura ClimatPro",
    publication: "AuraClimatpro",
    date: "March 4, 2026",
    dateISO: "2026-03-04",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/strategic-content-whitepaper-optimizing-winter-hvac-assets-for-aura-climatpro/",
    excerpt: "A comprehensive guide to winter heat pump maintenance and operation for Quebec homeowners — debunking cold-weather performance myths and providing practical strategies for filter care, snow clearance, defrost cycle management, and thermostat optimization to keep systems running efficiently through the harshest months.",
    tags: ["HVAC", "Heat Pump", "Winter", "Montreal", "Maintenance", "Energy Efficiency", "Quebec"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 39,
    title: "Livre blanc sur le contenu stratégique : Optimisation des actifs CVC hivernaux pour Aura ClimatPro",
    publication: "AuraClimatpro",
    date: "March 4, 2026",
    dateISO: "2026-03-04",
    wordCount: 1800,
    readTime: 9,
    url: "https://auraclimatpro.com/livre-blanc-sur-le-contenu-strategique-optimisation-des-actifs-cvc-hivernaux-pour-aura-climatpro/",
    excerpt: "Comment optimiser les systèmes de thermopompes pendant l'hiver québécois — démystifiant les mythes courants sur les performances par temps froid et fournissant des directives pratiques d'entretien pour les filtres, le dégagement de neige, les cycles de dégivrage et l'optimisation du thermostat pour une efficacité maximale toute la saison.",
    tags: ["HVAC", "Thermopompe", "Hiver", "Montreal", "Entretien", "Efficacité Énergétique", "French"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 40,
    title: "Preventing Ice Damming: Is Your Attic Ventilation Working?",
    publication: "Auxaire",
    date: "March 5, 2026",
    dateISO: "2026-03-05",
    wordCount: 1800,
    readTime: 9,
    url: "https://auxaire.com/2026/03/05/preventing-ice-damming-is-your-attic-ventilation-working/",
    excerpt: "Ice dams aren't just a winter nuisance — they're a sign of thermal failure in your attic. This guide explains how freeze-thaw cycles in Maritime climates drive ice dam formation, what proper intake and exhaust ventilation should look like, and how Nova Scotia, New Brunswick, and PEI rebate programs can offset the cost of fixing it.",
    tags: ["HVAC", "Insulation", "Attic", "Nova Scotia", "Winter", "Rebates", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 41,
    title: "The Early Bird Special: Why March is the Smartest Month for a Boston AC Tune-Up",
    publication: "ComfiTrust",
    date: "March 5, 2026",
    dateISO: "2026-03-05",
    wordCount: 1200,
    readTime: 6,
    url: "https://comfitrust.com/the-early-bird-special-why-march-is-the-smartest-month-for-a-boston-ac-tune-up/",
    excerpt: "Scheduling AC maintenance in March — before the summer rush hits — means shorter waits, better rebate availability, and catching winter dormancy damage before it compounds. This piece covers 2026 Mass Save changes, the R-410A phase-out, and why Boston's triple-deckers and brownstones need region-specific cooling strategies.",
    tags: ["HVAC", "Air Conditioning", "Boston", "Rebates", "Mass Save", "Heat Pump", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 42,
    title: "5 Mistakes to Avoid When Choosing a New AC Unit in Boston: Sizing, SEER2, and Rebate Traps",
    publication: "ComfiTrust",
    date: "March 17, 2026",
    dateISO: "2026-03-17",
    wordCount: 1800,
    readTime: 9,
    url: "https://comfitrust.com/5-mistakes-to-avoid-when-choosing-a-new-ac-unit-in-boston-sizing-seer2-and-rebate-traps/",
    excerpt: "Oversizing, ignoring SEER2 minimums, skipping ductwork assessment, missing the R-410A phase-out, and falling into Mass Save rebate traps — five costly mistakes Boston homeowners make when buying a new AC unit. This guide walks through each one with the Manual J and Manual D math that actually matters.",
    tags: ["HVAC", "Air Conditioning", "Boston", "Mass Save", "Rebates", "Energy Efficiency", "Buying Guide"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 43,
    title: "Supporting Local: Why Choosing a Boston-Based HVAC Firm Matters",
    publication: "ComfiTrust",
    date: "March 17, 2026",
    dateISO: "2026-03-17",
    wordCount: 1200,
    readTime: 6,
    url: "https://comfitrust.com/supporting-local-why-choosing-a-boston-based-hvac-firm-matters/",
    excerpt: "Local Boston HVAC contractors bring more than just proximity — they bring knowledge of historic district compliance, coastal corrosion challenges, and 2026 Mass Save rebate navigation that national chains simply don't have. Every $100 spent locally recirculates $50 back into Greater Boston, versus $15 with a national chain.",
    tags: ["HVAC", "Boston", "Mass Save", "Heat Pump", "Local Business", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 44,
    title: "How to Choose the Right HVAC System for Your Home: A 2026 Guide for BC Homeowners",
    publication: "AireEnergy",
    date: "May 2026",
    dateISO: "2026-05-01",
    wordCount: 1500,
    readTime: 8,
    url: "https://aireenergy.com/how-to-choose-the-right-hvac-system-for-your-home-a-2026-guide-for-bc-homeowners/",
    excerpt: "Choosing the right HVAC system in BC isn't a one-size-fits-all decision — coastal properties near Squamish and Delta need corrosion-resistant equipment, humid Surrey and Langley homes require strong dehumidification, and Vancouver's urban heat islands demand efficient nighttime operation. This 2026 guide covers Manual J sizing, variable-speed heat pumps, cold-climate options rated to -25°C, wildfire smoke filtration, and CleanBC rebates up to $24,000 for qualified homeowners.",
    tags: ["HVAC", "Heat Pump", "British Columbia", "Rebates", "Energy Efficiency", "CleanBC", "Buying Guide"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 45,
    title: "The Winnipeg HVAC Landscape: Climate Extremes, Smoke Records, and the Duct Cleaning Debate",
    publication: "WiserAire",
    date: "March 17, 2026",
    dateISO: "2026-03-17",
    wordCount: 1400,
    readTime: 7,
    url: "https://wiseraire.com/the-winnipeg-hvac-landscape-climate-extremes-smoke-records-and-the-duct-cleaning-debate/",
    excerpt: "Winnipeg logged 352 smoke hours in summer 2025 — roughly 25x the historical average — driving wildfire particulates deep into home HVAC systems. This piece unpacks when duct cleaning is genuinely necessary versus when it's a scam (spoofed local numbers, bait-and-switch pricing), how restricted airflow accelerates blower motor wear in Manitoba's extreme climate, and what WiserAire's rebate and financing options offer local homeowners.",
    tags: ["HVAC", "Duct Cleaning", "Winnipeg", "Air Quality", "Wildfire Smoke", "Manitoba", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 46,
    title: "Combi Boilers in BC: The Real Truth About Benefits, Costs, and Rebates",
    publication: "AireEnergy",
    date: "May 2026",
    dateISO: "2026-05-01",
    wordCount: 1300,
    readTime: 7,
    url: "https://aireenergy.com/combi-boilers-in-bc-the-real-truth-about-benefits-costs-and-rebates/",
    excerpt: "Combi boilers combine central heating and domestic hot water in one unit — but are they worth the $6,000–$18,000 install cost for BC homeowners? This guide covers coastal hard water scaling, freeze protection quirks, FortisBC rebates, CleanBC Energy Savings Program incentives, and multi-upgrade bonuses that can meaningfully offset upfront costs in Greater Vancouver.",
    tags: ["HVAC", "Boiler", "British Columbia", "Rebates", "CleanBC", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 47,
    title: "Winterpeg Survival Guide: How to Stop Ice Dams Before They Trash Your Home",
    publication: "WiserAire",
    date: "March 17, 2026",
    dateISO: "2026-03-17",
    wordCount: 1900,
    readTime: 10,
    url: "https://wiseraire.com/winterpeg-survival-guide-how-to-stop-ice-dams-before-they-trash-your-home/",
    excerpt: "Winnipeg's ~50 freeze-thaw cycles a year make ice dams a serious structural threat — especially in pre-1940s River Heights and Wolseley homes with complex rooflines and minimal insulation. This guide explains the thermodynamics behind dam formation, the 'Big Three' prevention strategies (R-60 insulation, 1:300 ventilation ratio, air sealing), and emergency interventions like calcium chloride channels when the dam is already forming.",
    tags: ["HVAC", "Insulation", "Winnipeg", "Winter", "Manitoba", "Home Improvement", "Attic"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 48,
    title: "The Boston Allergy Forecast: How HEPA and UV-C Upgrades Protect Your Home in 2026",
    publication: "ComfiTrust",
    date: "March 24, 2026",
    dateISO: "2026-03-24",
    wordCount: 2100,
    readTime: 11,
    url: "https://comfitrust.com/the-boston-allergy-forecast-how-hepa-and-uv-c-upgrades-protect-your-home-in-2026/",
    excerpt: "Boston's 2026 pollen season is hitting in a compressed 4–5 week burst after a prolonged winter — and historic triple-deckers and brownstones leak air in ways that defeat standard filters. This guide covers HEPA filtration (99.97% capture at 0.3 microns vs. 30% for standard), UV-C coil and air sterilization, neighborhood-level air quality disparities in Allston, Roxbury, and Back Bay, and current Mass Save rebates.",
    tags: ["HVAC", "Air Quality", "Boston", "HEPA", "Mass Save", "Rebates", "Allergy", "Health"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 49,
    title: "The April AC Switchover: 5 Checks Before You Power Up",
    publication: "WiserAire",
    date: "March 24, 2026",
    dateISO: "2026-03-24",
    wordCount: 1300,
    readTime: 7,
    url: "https://wiseraire.com/the-april-ac-switchover-5-checks-before-you-power-up/",
    excerpt: "Winnipeg homeowners switching from heat to AC face a real risk of compressor damage if they power up too early — the 60-Degree Rule exists for a reason. This checklist covers clearing road salt and debris from outdoor units without pressure-washing the fins, filter upgrades before spring dust season, thermostat testing, and Efficiency Manitoba rebates available for heat pump upgrades.",
    tags: ["HVAC", "Air Conditioning", "Winnipeg", "Manitoba", "Spring", "Maintenance", "Rebates"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 50,
    title: "The Spring \"Awakening\" Checklist for Maritime HVAC Systems",
    publication: "Auxaire",
    date: "March 27, 2026",
    dateISO: "2026-03-27",
    wordCount: 2100,
    readTime: 11,
    url: "https://auxaire.com/2026/03/27/the-spring-awakening-checklist-for-maritime-hvac-systems/",
    excerpt: "Salt creep corrodes aluminum fins and copper coils in Halifax, Moncton, and Charlottetown faster than anywhere inland — Maritime HVAC spring prep is a different beast. This checklist separates DIY tasks (filter checks, drain flushing with vinegar, debris clearing) from pro-only work (chemical coil neutralization, anti-corrosive shielding, refrigerant leak detection), plus 2026 rebates up to $30,000 in Nova Scotia and $16,500 in New Brunswick.",
    tags: ["HVAC", "Nova Scotia", "Maintenance", "Spring", "Rebates", "Heat Pump", "Maritime"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 51,
    title: "The Post-April 1 Rebate Reality Check",
    publication: "AireEnergy",
    date: "April 2026",
    dateISO: "2026-04-01",
    wordCount: 2200,
    readTime: 11,
    url: "https://aireenergy.com/the-post-april-1-rebate-reality-check/",
    excerpt: "April 1, 2026 marked a fundamental shift in BC's energy incentive landscape — CleanBC moved from universal rebates to income-qualified tiers, added property value caps ($1.23M for detached homes, $772K for condos), and BC Hydro raised rates 3.75%. This guide breaks down the four eligibility tiers, which Greater Vancouver homeowners now qualify, and how SEER2/HSPF2 standards affect what equipment counts for rebates.",
    tags: ["HVAC", "Rebates", "CleanBC", "British Columbia", "Heat Pump", "Energy Efficiency", "Buying Guide"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 52,
    title: "Analyse approfondie LogisVert 2026 – Maximiser vos subventions ce printemps",
    publication: "AuraClimatpro",
    date: "March 27, 2026",
    dateISO: "2026-03-27",
    wordCount: 2200,
    readTime: 11,
    url: "https://auraclimatpro.com/analyse-approfondie-logisvert-2026-maximiser-vos-subventions-ce-printemps/",
    excerpt: "LogisVert a transformé ses exigences en 2026 avec la certification ENERGY STAR obligatoire (en vigueur depuis novembre 2025) et un bonus de 5% pour les mesures multiples expirant le 30 avril. Ce guide couvre les subventions québécoises pour thermopompes (jusqu'à 6 700$), systèmes géothermiques et enveloppe du bâtiment, le programme ERR en Ontario, et les normes de performance à -15°C pour le couloir Gatineau-Montréal-Ottawa.",
    tags: ["HVAC", "Thermopompe", "Subventions", "Quebec", "French", "LogisVert", "Ottawa", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 53,
    title: "The 2026 LogisVert Deep Dive – Maximizing Your Spring Rebates",
    publication: "AuraClimatpro",
    date: "March 27, 2026",
    dateISO: "2026-03-27",
    wordCount: 1900,
    readTime: 10,
    url: "https://auraclimatpro.com/the-2026-logisvert-deep-dive-maximizing-your-spring-rebates/",
    excerpt: "The English companion to AuraClimatPro's LogisVert guide — covering Hydro-Québec's mandatory ENERGY STAR shift (November 2025), Quebec rebates for heat pumps ($6,700), geothermal ($750/1,000 BTU/h), and ETS ($15,000–$22,000), plus Ottawa ccASHP rebates up to $7,500. The April 30, 2026 deadline for the 5% multi-measure bonus and smaller upgrades makes spring the critical window for the Gatineau-Montreal-Ottawa corridor.",
    tags: ["HVAC", "Heat Pump", "Rebates", "Quebec", "Ottawa", "LogisVert", "Energy Efficiency", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 54,
    title: "The Spring Maintenance Pivot: Why Your Lower Mainland Home Needs a Strategic HVAC Tune-Up for 2026",
    publication: "AireEnergy",
    date: "April 6, 2026",
    dateISO: "2026-04-06",
    wordCount: 1700,
    readTime: 9,
    url: "https://aireenergy.com/the-spring-maintenance-pivot-why-your-lower-mainland-home-needs-a-strategic-hvac-tune-up-for-2026/",
    excerpt: "Vancouver's \"False Spring\" weather pattern and upcoming wildfire season make spring HVAC servicing a strategic move, not just routine upkeep. This guide covers coil cleaning, condensate line flushing, capacitor testing, pollen-season filter upgrades, and smoke readiness — with location-specific advice from coastal salt-air zones to urban heat islands, plus CleanBC rebates up to $19,000 for qualifying systems.",
    tags: ["HVAC", "Maintenance", "British Columbia", "CleanBC", "Rebates", "Air Quality", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 55,
    title: "Tree Pollen Survival: How to Actually Breathe in Winnipeg This Spring",
    publication: "WiserAire",
    date: "April 6, 2026",
    dateISO: "2026-04-06",
    wordCount: 1800,
    readTime: 9,
    url: "https://wiseraire.com/tree-pollen-survival-how-to-actually-breathe-in-winnipeg-this-spring/",
    excerpt: "Winnipeg's \"Spring of Deception\" brings white birch, bur oak, maple, and box elder pollen plus Big Thaw dust — a brutal combo for allergy sufferers. This guide navigates MERV ratings (13 is the Goldilocks zone), Photocatalytic Oxidation with the Lennox PureAir S, HRV vs. ERV tradeoffs for Manitoba homes, and why DIY filter upgrades can backfire through airflow complications.",
    tags: ["HVAC", "Air Quality", "Winnipeg", "Manitoba", "Allergy", "MERV", "Spring", "Health"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--mint))"
  },
  {
    id: 56,
    title: "The April MWRA Deadline: What the New Water Infrastructure Votes Mean for Your Tap",
    publication: "ComfiTrust",
    date: "April 6, 2026",
    dateISO: "2026-04-06",
    wordCount: 2100,
    readTime: 11,
    url: "https://comfitrust.com/the-april-mwra-deadline-what-the-new-water-infrastructure-votes-mean-for-your-tap/",
    excerpt: "Boston's $1.28 billion MWRA infrastructure plan — due for a vote April 30, 2026 — will trigger rate increases across municipalities (Boston at 1.50%, Somerville steeper) while aging combined sewers in Cambridge and Somerville create overflow and groundwater risks. This piece connects the dots between lead service lines, PFAS contamination, construction disruption through mid-2026, and the humidity and mold risks that groundwater infiltration poses to home HVAC systems.",
    tags: ["HVAC", "Boston", "Air Quality", "Water", "Home Improvement", "Health", "Infrastructure"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 57,
    title: "The Air Exchanger Ultimatum – Is Your Home Compliance-Ready?",
    publication: "AuraClimatpro",
    date: "April 6, 2026",
    dateISO: "2026-04-06",
    wordCount: 2100,
    readTime: 11,
    url: "https://auraclimatpro.com/the-air-exchanger-ultimatum-is-your-home-compliance-ready/",
    excerpt: "Quebec's Construction Code and Ontario's 2024 Building Code updates now mandate mechanical ventilation — and non-compliance has real estate and insurance consequences. This guide compares HRV vs. ERV technologies for regional climates, covers new radon sub-floor depressurization requirements, LogisVert and Ontario Home Renovation Savings rebates, and AuraClimatPro's seven-step diagnostic for verifying air exchanger compliance.",
    tags: ["HVAC", "Air Quality", "Quebec", "Ottawa", "HRV", "Compliance", "Rebates", "Health"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 58,
    title: "L'ultimatum des échangeurs d'air – Votre habitation est-elle conforme?",
    publication: "AuraClimatpro",
    date: "April 6, 2026",
    dateISO: "2026-04-06",
    wordCount: 2100,
    readTime: 11,
    url: "https://auraclimatpro.com/lultimatum-des-echangeurs-dair-votre-habitation-est-elle-conforme/",
    excerpt: "Les nouveaux codes du bâtiment du Québec et de l'Ontario 2024 rendent la ventilation mécanique obligatoire — et la non-conformité entraîne des conséquences immobilières et d'assurance. Ce guide compare VRC et VRE selon les climats régionaux, couvre les nouvelles exigences de dépressurisation pour le radon, les subventions LogisVert et le programme Rénovation domiciliaire de l'Ontario (jusqu'à 14 000$), et le diagnostic en sept étapes d'AuraClimatPro.",
    tags: ["HVAC", "Qualité de l'air", "Quebec", "Ottawa", "VRC", "Conformité", "Subventions", "French"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 59,
    title: "Navigating the Nova Scotia Rebate Standby List – What Now?",
    publication: "Auxaire",
    date: "May 1, 2026",
    dateISO: "2026-05-01",
    wordCount: 2500,
    readTime: 13,
    url: "https://auxaire.com/2026/05/01/navigating-the-nova-scotia-rebate-standby-list-what-now/",
    excerpt: "The federal OHPA program hit capacity on February 11, 2026, leaving Nova Scotia homeowners in a queue rather than rejected outright. This guide maps alternative paths: the Moderate Income Rebate (up to $15,000 with income thresholds $37,260–$126,500+), thermal envelope upgrades with rebates up to $5,000, PACE financing at 4.75% in Halifax and Bridgewater, and cold-climate heat pump specs (HSPF2 6.6+, SEER2 15.2+) needed to qualify when funding opens.",
    tags: ["HVAC", "Heat Pump", "Nova Scotia", "Rebates", "Energy Efficiency", "Maritime", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 60,
    title: "Why Attic Insulation is the Secret to Unlocking the $8,500 Mass Save Heat Pump Rebate",
    publication: "ComfiTrust",
    date: "May 4, 2026",
    dateISO: "2026-05-04",
    wordCount: 2100,
    readTime: 11,
    url: "https://comfitrust.com/why-attic-insulation-is-the-secret-to-unlocking-the-8500-mass-save-heat-pump-rebate/",
    excerpt: "The $8,500 Mass Save heat pump rebate has a weatherization prerequisite most homeowners miss — attic insulation. Proper insulation reduces heating loads by 20–40%, enabling a smaller system that qualifies for an extra $500 sizing bonus, while the Stack Effect math shows exactly why skipping this step forces heat pumps to work inefficiently. Also covers the R-410A ban (January 2026), R-32/R-454B compliant units, and 0% financing for income-eligible Boston households.",
    tags: ["HVAC", "Heat Pump", "Boston", "Mass Save", "Rebates", "Insulation", "Attic", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 61,
    title: "Earth Day and the Decarbonization Roadmap: What It Means for Your Home in Greater Vancouver",
    publication: "AireEnergy",
    date: "April 2026",
    dateISO: "2026-04-22",
    wordCount: 2400,
    readTime: 12,
    url: "https://aireenergy.com/earth-day-and-the-decarbonization-roadmap-what-it-means-for-your-home-in-greater-vancouver/",
    excerpt: "BC's CleanBC plan targets 40% emission reductions by 2030 and net-zero by 2050 — and Greater Vancouver homeowners are central to that roadmap. This Earth Day guide covers replacing gas systems with electric alternatives on BC's hydroelectric grid, heat pump rebates up to $24,000, tankless water heaters, solar and battery storage integration, EV charging, and a practical Surrey home retrofit scenario showing how these upgrades stack.",
    tags: ["HVAC", "Heat Pump", "British Columbia", "CleanBC", "Rebates", "Solar", "Energy Efficiency", "Decarbonization"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 62,
    title: "Spring Runoff & Basement Humidity: Is Your Winnipeg HVAC Doing Enough?",
    publication: "WiserAire",
    date: "May 6, 2026",
    dateISO: "2026-05-06",
    wordCount: 1800,
    readTime: 9,
    url: "https://wiseraire.com/spring-runoff-basement-humidity-is-your-winnipeg-hvac-doing-enough/",
    excerpt: "Winnipeg's Red River Valley clay soil creates intense hydrostatic pressure during spring snowmelt, forcing moisture through foundations while standard AC short-cycles and fails to dehumidify properly. This guide covers the warning signs (window fog, efflorescence, damp furnace filters), HRV's \"20/40 Setting\" for shoulder season, GREE heat pump Dry Function, the 5-Foot Rule for exterior snow management, and Efficiency Manitoba rebates.",
    tags: ["HVAC", "Humidity", "Winnipeg", "Manitoba", "Spring", "HRV", "Basement", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 63,
    title: "The Gatineau-Montreal Pollen Calendar – HVAC as Your First Line of Defense",
    publication: "AuraClimatpro",
    date: "May 7, 2026",
    dateISO: "2026-05-07",
    wordCount: 2100,
    readTime: 11,
    url: "https://auraclimatpro.com/the-gatineau-montreal-pollen-calendar-hvac-as-your-first-line-of-defense/",
    excerpt: "The Gatineau-Montreal corridor faces three distinct pollen waves — tree, grass, and ragweed — amplified by the Valley Effect and urban heat islands extending each season. This guide recommends MERV 13 as the allergy sweet spot, covers HRV/ERV integration, UV-C germicidal systems, bio-sludge remediation, and the 7-to-1 rule for peak pollen hours, positioning HVAC as the primary defense for corridor residents.",
    tags: ["HVAC", "Air Quality", "Montreal", "Ottawa", "Allergy", "MERV", "HRV", "Health"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 64,
    title: "Le calendrier du pollen Gatineau-Montréal – le CVC comme première ligne de défense",
    publication: "AuraClimatpro",
    date: "May 8, 2026",
    dateISO: "2026-05-08",
    wordCount: 2200,
    readTime: 11,
    url: "https://auraclimatpro.com/le-calendrier-du-pollen-gatineau-montreal-le-cvc-comme-premiere-ligne-de-defense/",
    excerpt: "Le corridor Gatineau-Montréal subit trois vagues polliniques de mars à octobre — arbres printaniers (érable, bouleau, chêne, frêne), graminées estivales et l'ambroisie responsable de 90% des rhinites saisonnières. Ce guide couvre les cotes MERV (13 recommandé, capturant 90% des allergènes), les VRC, les lampes UV-C germicides, la bio-boue sur les serpentins de refroidissement, et l'effet d'îlot de chaleur urbain qui prolonge les saisons de 2-3 semaines.",
    tags: ["HVAC", "Qualité de l'air", "Montreal", "Ottawa", "Allergie", "MERV", "VRC", "French"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 66,
    title: "The 'No-Audit' Rebate: Why Path B is the Total Game-Changer for Ontario Homeowners in 2026",
    publication: "ConstantHomeComfort",
    date: "May 11, 2026",
    dateISO: "2026-05-11",
    wordCount: 1200,
    readTime: 6,
    url: "https://www.constanthomecomfort.com/news-detail?pid=4&slug=the-no-audit-rebate-why-path-b-is-the-total-game-changer-for-ontario-homeowners-in-2026",
    excerpt: "Ontario's Path B rebate program is a breakthrough for homeowners who want to upgrade to heat pumps without the barrier of a mandatory energy audit — this guide breaks down how Path B works, who qualifies, and why it's the most accessible route to stacking federal and provincial incentives for HVAC upgrades in 2026.",
    tags: ["Rebates", "Ontario", "Heat Pump", "HVAC", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 67,
    title: "Heat Pumps for Summer Cooling: The $2,000 Rebate Winnipeg Homeowners Didn't Know About",
    publication: "WiserAire",
    date: "May 13, 2026",
    dateISO: "2026-05-13",
    wordCount: 1800,
    readTime: 9,
    url: "https://wiseraire.com/heat-pumps-for-summer-cooling-the-2000-rebate-winnipeg-homeowners-didnt-know-about/",
    excerpt: "Winnipeg homeowners can access a $2,000 Efficiency Manitoba rebate by switching from standard air conditioners to high-efficiency heat pumps. The article details the operational advantages of variable-speed heat pumps — improved humidity control and lower energy costs — and addresses cold-climate performance concerns by recommending hybrid systems that pair heat pumps with gas furnaces for winter reliability.",
    tags: ["HVAC", "Heat Pump", "Winnipeg", "Manitoba", "Rebates", "Air Conditioning", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 70,
    title: "Pre-Summer AC Performance & Coil Cleaning: The Ultimate Guide to Staying Cool and Saving Money in Ontario",
    publication: "ConstantHomeComfort",
    date: "May 22, 2026",
    dateISO: "2026-05-22",
    wordCount: 2800,
    readTime: 14,
    url: "https://www.constanthomecomfort.com/news-detail?pid=1&slug=pre-summer-ac-performance-coil-cleaning-the-ultimate-guide-to-staying-cool-and-saving-money-in-ontario",
    excerpt: "Dirty evaporator and condenser coils can reduce AC cooling capacity by up to 30% and spike energy consumption by 37% — and neglected systems risk compressor failure ($1,200–$2,500) long before the summer heat hits. This guide walks Ontario homeowners through the thermodynamics of coil contamination, the dangerous domino effect from dirty coils to frozen systems, indoor air quality risks (including \"dirty sock\" mold syndrome), and a full professional maintenance checklist. Rebate opportunities include up to $12,000 through the Home Renovation Savings Program and a $59 limited-time tune-up special for GTA homeowners.",
    tags: ["HVAC", "Air Conditioning", "Ontario", "Maintenance", "Coil Cleaning", "Rebates", "Air Quality", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 69,
    title: "R-410A Sunset: Navigating the New A2L Refrigerants",
    publication: "ConstantHomeComfort",
    date: "May 15, 2026",
    dateISO: "2026-05-15",
    wordCount: 1200,
    readTime: 6,
    url: "https://www.constanthomecomfort.com/news-detail?pid=4&slug=r-410a-sunset-navigating-the-new-a2l-refrigerants",
    excerpt: "As of January 1, 2026, Canada banned new HVAC equipment using R-410A (GWP 2,088) under the Kigali Amendment — replacing it with A2L refrigerants like R-32 and R-454B, which meet the new 750 GWP ceiling. This guide breaks down the flammability realities of A2L fluids, the key differences between R-32 and R-454B, TSSA compliance updates, and why there are zero drop-in retrofit options for existing systems. Ontario homeowners can offset the 15–30% equipment cost premium through the 2026 Home Renovation Savings Program, with rebates up to $7,500 — but contractor registration closes May 31, 2026.",
    tags: ["HVAC", "Refrigerants", "Ontario", "R-410A", "Heat Pump", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 68,
    title: "Why Your BC Home is Your Best Defense This Allergy Season",
    publication: "AireEnergy",
    date: "May 2026",
    dateISO: "2026-05-14",
    wordCount: 2000,
    readTime: 10,
    url: "https://aireenergy.com/why-your-bc-home-is-your-best-defense-this-allergy-season/",
    excerpt: "BC homeowners can transform their residences into sanctuaries from seasonal allergens and wildfire smoke by implementing proper indoor air quality systems — indoor air can be 5–10x more polluted than outside without proper filtration. The article outlines a three-pillar approach: high-efficiency filtration, UV-C technology, and humidity control, with substantial 2026 rebates available through government programs to offset upgrade costs.",
    tags: ["HVAC", "Air Quality", "British Columbia", "Allergy", "HEPA", "Rebates", "Health", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 82,
    title: "The June 1st Efficiency Check: Navigating New HSPF2 Standards for Winnipeg Homeowners",
    publication: "WiserAire",
    date: "June 11, 2026",
    dateISO: "2026-06-11",
    wordCount: 3800,
    readTime: 19,
    url: "https://wiseraire.com/the-june-1st-efficiency-check-navigating-new-hspf2-standards-for-winnipeg-homeowners/",
    excerpt: "June 1st kicks off Winnipeg's first high-load cooling season under HSPF2 and SEER2 — tougher real-world tests using actual ductwork resistance, not lab conditions (a HSPF2 8.9 on the new scale beats an old HSPF 10). The critical threshold for Efficiency Manitoba's $2,000 rebate is HSPF2 Region V 6.6, not the US Region IV rating contractors sometimes quote. Covers dual-fuel hybrid setups for -35°C polar vortex winters, CSA-F280-12 heat load calculations, snow stand installs over concrete pads, cottonwood fin-clogging prevention, R-410A phase-down to R-32/R-454B, and the full rebate stack: $2,000 ducted, $1,500 ductless, $12,500 HEEL loan, $100 F280 sizing bonus.",
    tags: ["HVAC", "Heat Pump", "Winnipeg", "Manitoba", "HSPF2", "Rebates", "Energy Efficiency", "Dual-Fuel"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--mint))"
  },
  {
    id: 81,
    title: "The Energy Savings Program Deep Dive: How GVA Homeowners Are Scoring $19,000 for Home Upgrades",
    publication: "AireEnergy",
    date: "June 10, 2026",
    dateISO: "2026-06-10",
    wordCount: 2500,
    readTime: 13,
    url: "https://aireenergy.com/the-energy-savings-program-deep-dive-how-gva-homeowners-are-scoring-19000-for-home-upgrades/",
    excerpt: "BC Hydro's 3.75% and FortisBC's 5%+ rate hikes are squeezing GVA budgets — but CleanBC's Energy Savings Program delivers instant rebates (deducted at invoice, not mailed later) up to $19,000. Income tiers cover families of four earning up to $185,620, with Level 1 households (under $87,350) often paying $0 out of pocket. Covers heat pump sizing for Squamish's -30°C cold snaps, GREE Charmo anti-corrosion coatings for Delta salt air, ductless retrofits for Burnaby's 1960s–70s homes (one 51-unit complex cut heating electricity by 70%), plus window ($9,500), panel upgrade ($5,000), and health hazard remediation rebates.",
    tags: ["HVAC", "Heat Pump", "British Columbia", "CleanBC", "Rebates", "Energy Efficiency", "Mini-Split", "Buying Guide"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 80,
    title: "Whole-Home vs. Partial-Home Heat Pumps: Which 2026 Configuration Wins for Boston Multi-Families?",
    publication: "ComfiTrust",
    date: "June 9, 2026",
    dateISO: "2026-06-09",
    wordCount: 1300,
    readTime: 7,
    url: "https://comfitrust.com/whole-home-vs-partial-home-heat-pumps-which-2026-configuration-wins-for-boston-multi-families/",
    excerpt: "Boston's BERDO 2.0 fines ($234/metric ton, potentially six figures annually for mid-sized Back Bay buildings) are forcing multi-family owners to act. This guide breaks down the 2026 rebate math — whole-home at $2,650/ton up to $8,500 vs. hybrid at $1,125/ton — explains why R-32 systems (Gree Sapphire, Mitsubishi M-series) deliver 10% more heat during a polar vortex, covers the Heat Pump Rate that drops electricity from $0.34 to $0.18/kWh, and walks through the one-to-one metering rules that prevent costly cross-metering lawsuits.",
    tags: ["HVAC", "Heat Pump", "Boston", "Massachusetts", "Mass Save", "Rebates", "BERDO", "Multi-Family"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 79,
    title: "Solar Readiness: Preparing Your Home Envelope for Efficiency Upgrades",
    publication: "WiserAire",
    date: "June 8, 2026",
    dateISO: "2026-06-08",
    wordCount: 3000,
    readTime: 15,
    url: "https://wiseraire.com/solar-readiness-preparing-your-home-envelope-for-efficiency-upgrades/",
    excerpt: "WiserAire's 'Leaky Bucket Syndrome' principle: sealing Winnipeg's drafty pre-1999 homes to R-60 and eliminating stack-effect air leaks can shrink a required solar array by 30%, saving thousands in panels. This guide covers Climate Zone 7A insulation standards, the 1.9 kPa snow load structural certification, pre-installing a solar raceway conduit, 200-amp panel upgrades, cold-climate heat pump synergy, and Efficiency Manitoba's $0.50/watt solar rebate (up to $5,000) plus the HEEL loan up to $20,000 at 6.2%.",
    tags: ["Solar", "Energy Efficiency", "Winnipeg", "Manitoba", "Insulation", "HVAC", "Rebates", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 78,
    title: "The A2L Transition: Everything Boston Homeowners Need to Know About the New Refrigerant Standards",
    publication: "ComfiTrust",
    date: "June 5, 2026",
    dateISO: "2026-06-05",
    wordCount: 2800,
    readTime: 14,
    url: "https://comfitrust.com/the-a2l-transition-everything-boston-homeowners-need-to-know-about-the-new-refrigerant-standards/",
    excerpt: "R-410A is banned from new installs and the Mass Save rebate list as of January 2026 — and with the EPA slashing R-410A production by 40%, recharging a leaky old system is becoming a money trap. This guide demystifies A2L refrigerants (R-32 and R-454B, GWP under 700), explains the built-in 'sniffer' leak detection systems in modern units, addresses Boston triple-decker and brownstone retrofit challenges, and breaks down the $8,500 Mass Save rebate, 0% HEAT loan up to $25,000, and the R-32 vs. R-454B brand split.",
    tags: ["HVAC", "Refrigerants", "Boston", "Massachusetts", "R-410A", "Heat Pump", "Mass Save", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 77,
    title: "High-Efficiency Cooling for BC Condos and Townhomes: The 2026 Homeowner's Survival Guide",
    publication: "AireEnergy",
    date: "June 4, 2026",
    dateISO: "2026-06-04",
    wordCount: 3000,
    readTime: 15,
    url: "https://aireenergy.com/high-efficiency-cooling-for-bc-condos-and-townhomes-the-2026-homeowners-survival-guide/",
    excerpt: "Since the 2021 heat dome, high-efficiency cooling has become a survival necessity for BC condo and townhome owners — but strata bylaws, Bill 22 Electrical Planning Reports, and 20 dB 'stealth ban' noise limits make the path complicated. This guide covers ductless mini-splits as the condo solution (19–23 dB, wildfire smoke filtration, 300% heating efficiency), region-specific advice for Langley heat traps, Delta salt air (Blue Fin coatings), and Squamish cold-climate needs, plus BC Hydro rebates up to $2,250, CleanBC income-qualified up to $24,000, and the $5,000 repair-vs-replace rule.",
    tags: ["HVAC", "Heat Pump", "British Columbia", "Mini-Split", "Rebates", "CleanBC", "Condo", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 76,
    title: "Tankless Water Heaters: Why Spring is the Best Time to Upgrade Your Winnipeg Home",
    publication: "WiserAire",
    date: "June 3, 2026",
    dateISO: "2026-06-03",
    wordCount: 2400,
    readTime: 12,
    url: "https://wiseraire.com/tankless-water-heaters-why-spring-is-the-best-time-to-upgrade-your-winnipeg-home/",
    excerpt: "Winnipeg tanks hit spring already beaten up — months of heating 1–4°C Shoal Lake water causes mineral sediment buildup, the \"kettle effect,\" and thermal fatigue, right as spring melt raises basement flooding risk. Tankless units mount 4–5 feet up the wall to clear the flood zone, spring shoulder season means more precise installs, and the Manitoba Hydro HEEL loan (up to $7,500, no down payment) paired with 24–34% standby heat loss savings makes the switch financially compelling. WiserAire recommends Rinnai and Navien stainless steel models for Winnipeg's hard water.",
    tags: ["HVAC", "Tankless Water Heater", "Winnipeg", "Manitoba", "Spring", "Rebates", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 75,
    title: "Hydro Arbitrage: ULO Rates & Smart Systems",
    publication: "ConstantHomeComfort",
    date: "June 2, 2026",
    dateISO: "2026-06-02",
    wordCount: 3600,
    readTime: 18,
    url: "https://www.constanthomecomfort.com/news-detail?pid=4&slug=hydro-arbitrage-ulo-rates-smart-systems",
    excerpt: "Ontario's ULO plan creates a 35.2¢/kWh spread between overnight (3.9¢) and evening peak (39.1¢) rates — and smart thermostats like the Ecobee and Nest can exploit it through predictive thermal pre-conditioning, coasting homes through the expensive 4–9 p.m. window on stored heat or cool air. Paired with a dual-fuel heat pump and gas furnace setup, this hydro arbitrage strategy saves over $1,500 annually, with Ontario's Home Renovation Savings Program rebates (up to $7,500 for heat pumps) offsetting the upgrade cost.",
    tags: ["Energy Efficiency", "Ontario", "Smart Home", "Heat Pump", "Utility Rates", "HVAC", "Rebates", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 74,
    title: "Engineered Home Defense: Optimizing Indoor Air Quality Against Allergy Waves and Wildfire Smoke Across Ontario",
    publication: "ConstantHomeComfort",
    date: "June 1, 2026",
    dateISO: "2026-06-01",
    wordCount: 3700,
    readTime: 19,
    url: "https://www.constanthomecomfort.com/news-detail?pid=1&slug=engineered-home-defense-optimizing-indoor-air-quality-against-allergy-waves-and-wildfire-smoke-across-ontario",
    excerpt: "Ontario's 2026 pollen explosion — triggered by synchronized tree pollination colliding with early wildfire smoke pushing PM2.5 past 150 μg/m³ — is overwhelming standard home ventilation. This deep-dive covers region-specific risks across the GTA, compares air purification tiers from $80 portable units to $2,100 whole-home multi-stage systems, explains the MERV and HVAC strain math, and maps Ontario's Home Renovation Savings Program rebates (up to $7,500 for heat pumps) to build a science-backed indoor air defense.",
    tags: ["HVAC", "Air Quality", "Ontario", "Allergy", "Wildfire Smoke", "MERV", "Health", "Rebates", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 73,
    title: "Navigating the 2026 Mass Save Roadmap: How to Secure the New $500 Sizing Bonus",
    publication: "ComfiTrust",
    date: "May 29, 2026",
    dateISO: "2026-05-29",
    wordCount: 2100,
    readTime: 11,
    url: "https://comfitrust.com/navigating-the-2026-mass-save-roadmap-how-to-secure-the-new-500-sizing-bonus/",
    excerpt: "Mass Save's 2026 update adds a $500 bonus for properly sized heat pump installations — but claiming it requires a Manual J load calculation and R-454B/R-32 compliant equipment. This guide walks Boston homeowners through the technical requirements, explains why oversized systems disqualify the bonus, and maps the full rebate stack available this year.",
    tags: ["HVAC", "Heat Pump", "Boston", "Mass Save", "Rebates", "Massachusetts", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 72,
    title: "Economic Implications of Utility Rate Hikes and High-Efficiency Cooling ROI",
    publication: "WiserAire",
    date: "May 28, 2026",
    dateISO: "2026-05-28",
    wordCount: 2100,
    readTime: 11,
    url: "https://wiseraire.com/economic-implications-of-utility-rate-hikes-and-high-efficiency-cooling-roi/",
    excerpt: "Manitoba Hydro's 4.0% rate hike effective January 2026 has tipped the ROI math decisively toward high-efficiency AC upgrades — modern systems can cut annual cooling costs by roughly 50%, and stacking Efficiency Manitoba rebates with manufacturer incentives brings the payback window within reach for most Winnipeg homeowners.",
    tags: ["HVAC", "Air Conditioning", "Energy Efficiency", "Manitoba", "Winnipeg", "Rebates", "Utility Rates"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 71,
    title: "The 2026 Pollen Surge: Turning Your Maritime Heat Pump into an Allergy Shield",
    publication: "Auxaire",
    date: "May 27, 2026",
    dateISO: "2026-05-27",
    wordCount: 2100,
    readTime: 11,
    url: "https://auxaire.com/2026/05/27/the-2026-pollen-surge-turning-your-maritime-heat-pump-into-an-allergy-shield/",
    excerpt: "Maritime Canada's 2026 pollen season is unusually severe — and homeowners can turn their heat pump into a frontline allergy defense. This guide covers MERV filter ratings, high-performance systems from Lennox and GREE, and how to stack government rebates across Nova Scotia, New Brunswick, and PEI to offset the cost of an upgrade.",
    tags: ["HVAC", "Heat Pump", "Allergy", "Nova Scotia", "Rebates", "Air Quality", "Maritime", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 70,
    title: "The Spring Runoff and Water Purification: A Comprehensive Analysis for British Columbia Homeowners",
    publication: "AireEnergy",
    date: "May 2026",
    dateISO: "2026-05-26",
    wordCount: 1800,
    readTime: 9,
    url: "https://aireenergy.com/the-spring-runoff-and-water-purification-a-comprehensive-analysis-for-british-columbia-homeowners/",
    excerpt: "BC's spring freshet creates a convergence of water quality threats — turbidity from glacial silt, microbial hazards like Giardia and Cryptosporidium, nitrate runoff, and PFAS contamination — with risks varying significantly by watershed across Greater Vancouver. This guide covers region-specific contaminant profiles, reverse osmosis, UV disinfection, and seasonal maintenance steps to protect residential water systems during peak runoff season.",
    tags: ["Water Quality", "British Columbia", "Spring", "PFAS", "Filtration", "Health", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 65,
    title: "Beyond the Filter: A Deep Dive into PFAS and Microplastic Removal for Massachusetts Homes",
    publication: "ComfiTrust",
    date: "May 11, 2026",
    dateISO: "2026-05-11",
    wordCount: 2100,
    readTime: 11,
    url: "https://comfitrust.com/beyond-the-filter-a-deep-dive-into-pfas-and-microplastic-removal-for-massachusetts-homes/",
    excerpt: "This comprehensive guide examines the growing concerns of PFAS (\"forever chemicals\") and microplastics in Massachusetts water systems, exploring their health impacts and evaluating filtration technologies like reverse osmosis and activated carbon to protect residential water quality.",
    tags: ["Water Quality", "PFAS", "Massachusetts", "Filtration", "Home Health", "Boston", "Water Treatment"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  }
];
