const BLOGS = [
  {
    id: 1,
    title: "Technoeconomic Analysis: The 2026 Shift to Smart HVAC Standards in Greater Boston",
    publication: "ComfiTrust",
    date: "January 5, 2026",
    dateISO: "2026-01-05",
    wordCount: 1320,
    readTime: 7,
    url: "https://comfitrust.com/technoeconomic-analysis-the-2026-shift-to-smart-hvac-standards-in-greater-boston/",
    excerpt: "As of 2026, Boston's HVAC sector has crossed the tipping point where system intelligence replaces mechanical reliability as the primary quality metric — driven by BERDO emissions mandates, R-410A refrigerant phase-outs, and AI-powered predictive comfort systems reshaping how Greater Boston homes manage climate and energy.",
    tags: ["HVAC", "Smart Home", "Energy Efficiency", "Boston", "AI", "Real Estate"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 2,
    title: "The Emergency 'No-Heat' Playbook: What to Do During a Polar Vortex",
    publication: "ComfiTrust",
    date: "January 8, 2026",
    dateISO: "2026-01-08",
    wordCount: 973,
    readTime: 5,
    url: "https://comfitrust.com/the-emergency-no-heat-playbook-what-to-do-during-a-polar-vortex/",
    excerpt: "When a Polar Vortex hits Greater Boston, it's a brutal test of your home's high-efficiency heating system. This step-by-step emergency playbook covers safety triage, PVC vent checks, error code decoding for Gree, Mitsubishi, and Bosch systems, and how to protect your pipes — so you're never left in the cold at 2 AM.",
    tags: ["HVAC", "Emergency", "Heat Pump", "Boston", "Winter", "Troubleshooting"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 3,
    title: "Massachusetts Heat Pump Reality Check: Do They Really Work at -15°F?",
    publication: "ComfiTrust",
    date: "January 12, 2026",
    dateISO: "2026-01-12",
    wordCount: 1034,
    readTime: 5,
    url: "https://comfitrust.com/massachusetts-heat-pump-reality-check-do-they-really-work-at-15f/",
    excerpt: "A technical reality check on air-source heat pumps in New England winters — examining COP ratings across temperature ranges, EVI and Flash Injection technology, brand comparisons across Mitsubishi, Bosch, and Daikin, and Massachusetts-specific rebates and the No-Cost Heat Pump Program.",
    tags: ["HVAC", "Heat Pump", "Massachusetts", "Winter", "Rebates", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 4,
    title: "Nova Scotia Rebate Update: The 2026 Guide",
    publication: "Auxaire",
    date: "January 13, 2026",
    dateISO: "2026-01-13",
    wordCount: 1573,
    readTime: 8,
    url: "https://auxaire.com/2026/01/13/nova-scotia-rebate-update-the-2026-guide/",
    excerpt: "Nova Scotia homeowners can stack up to $30,000 in 2026 rebates for switching from oil to heat pumps — but major programs are expected to deplete early. This guide covers OHPA grants, income-based top-ups, Efficiency NS home assessments, supplemental insulation rebates, and 0% PACE financing options.",
    tags: ["Rebates", "Nova Scotia", "Heat Pump", "Energy Efficiency", "HVAC", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 5,
    title: "The \"Burning Plastic\" Smell: Is Your Furnace Safe?",
    publication: "WiserAire",
    date: "January 14, 2026",
    dateISO: "2026-01-14",
    wordCount: 1566,
    readTime: 8,
    url: "https://wiseraire.com/the-burning-plastic-smell-is-your-furnace-safe/",
    excerpt: "That burning plastic smell from your furnace could be dust — or a failing blower motor, electrical arcing, or a cracked heat exchanger leaking carbon monoxide. This Winnipeg-focused guide walks through the three main causes, emergency shutdown steps, and when to call for 24/7 repair.",
    tags: ["HVAC", "Furnace", "Safety", "Winnipeg", "Carbon Monoxide", "Troubleshooting"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 6,
    title: "Is Your Heat Pump Ready for -30°C? A Maritime Survival Guide",
    publication: "Auxaire",
    date: "January 9, 2026",
    dateISO: "2026-01-09",
    wordCount: 1346,
    readTime: 7,
    url: "https://auxaire.com/2026/01/09/is-your-heat-pump-ready-for-30c-a-maritime-survival-guide/",
    excerpt: "Modern cold-climate heat pumps can hold the line at -30°C — but only if they're properly sized, coated for coastal salt air, and backed by the right dual-fuel strategy. This Maritime survival guide covers Enhanced Vapor Injection technology, anti-corrosion coatings, frost management, and 2026 rebate programs offering up to $30,000 in Nova Scotia.",
    tags: ["HVAC", "Heat Pump", "Nova Scotia", "Winter", "Rebates", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 7,
    title: "Navigating the 2026 Mass Save Rebate Reductions: What You Need to Know NOW",
    publication: "ComfiTrust",
    date: "January 15, 2026",
    dateISO: "2026-01-15",
    wordCount: 1515,
    readTime: 8,
    url: "https://comfitrust.com/navigating-the-2026-mass-save-rebate-reductions-what-you-need-to-know-now/",
    excerpt: "Massachusetts homeowners face a \"triple hit\" to heat pump budgets in 2026 as Mass Save slashes maximum rebates from $10,000 to $8,500, new tonnage-based calculations and refrigerant compliance rules tighten eligibility, and federal Section 25C tax credits expire — with a breakdown of what to do before the cuts take full effect.",
    tags: ["HVAC", "Heat Pump", "Massachusetts", "Rebates", "Energy Efficiency", "Mass Save"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 8,
    title: "Manitoba Hydro Bills Too High? 5 Ways to Optimize Your Furnace Today",
    publication: "WiserAire",
    date: "January 16, 2026",
    dateISO: "2026-01-16",
    wordCount: 1761,
    readTime: 9,
    url: "https://wiseraire.com/manitoba-hydro-bills-too-high-5-ways-to-optimize-your-furnace-today/",
    excerpt: "Five practical strategies for cutting Manitoba Hydro bills through furnace optimization — from filter swaps and duct sealing to smart thermostats and intelligent monitoring — with cost estimates and expected savings for each upgrade.",
    tags: ["HVAC", "Furnace", "Energy Efficiency", "Winnipeg", "Manitoba", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 9,
    title: "Why Your Boston Home Has Hot and Cold Spots (and How to Fix Them)",
    publication: "ComfiTrust",
    date: "January 20, 2026",
    dateISO: "2026-01-20",
    wordCount: 1436,
    readTime: 7,
    url: "https://comfitrust.com/why-your-boston-home-has-hot-and-cold-spots-and-how-to-fix-them/",
    excerpt: "Boston homes battle temperature imbalances caused by the stack effect, aging ductwork, and urban heat islands — this guide covers professional air balancing, zoning systems, and ductless mini-splits as targeted fixes, with Mass Save rebates that can offset upgrade costs.",
    tags: ["HVAC", "Boston", "Heat Pump", "Energy Efficiency", "Mass Save", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 10,
    title: "Where Should You Actually Put CO Detectors in a Split-Level Home?",
    publication: "WiserAire",
    date: "January 22, 2026",
    dateISO: "2026-01-22",
    wordCount: 1036,
    readTime: 5,
    url: "https://wiseraire.com/where-should-you-actually-put-co-detectors-in-a-split-level-home/",
    excerpt: "CO doesn't sink or rise — it follows airflow, which makes split-level homes especially tricky. This guide covers the exact placement rules for bedroom doors, garage entries, and mechanical spaces, plus the common installation mistakes that leave dangerous blind spots.",
    tags: ["Safety", "Carbon Monoxide", "HVAC", "Furnace", "Winnipeg", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 11,
    title: "Why Is My Furnace Blowing Cold Air?",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1197,
    readTime: 6,
    url: "https://auraclimatpro.com/why-is-my-furnace-blowing-cold-air/",
    excerpt: "A furnace blowing cold air isn't always a crisis — seven common culprits from thermostat mode to dirty filters can be ruled out before calling a tech. This Montreal-focused guide walks through each cause and the DIY fix or escalation threshold for each.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 12,
    title: "Pourquoi mon fournaise souffle-t-elle de l'air froid?",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1415,
    readTime: 7,
    url: "https://auraclimatpro.com/pourquoi-mon-fournaise-souffle-t-elle-de-lair-froid/",
    excerpt: "Une fournaise qui souffle de l'air froid n'est pas toujours en panne — sept causes courantes, du réglage du thermostat au filtre encrassé, peuvent être éliminées avant d'appeler un technicien. Guide de dépannage pour propriétaires montréalais.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "French", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 13,
    title: "Stop Cringing at Your Energy Bill: 10 Ways to Stay Warm for Less",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1022,
    readTime: 5,
    url: "https://auraclimatpro.com/stop-cringing-at-your-energy-bill-10-ways-to-stay-warm-for-less/",
    excerpt: "Ten budget-friendly strategies to cut winter heating costs without sacrificing comfort — from weatherstripping and programmable thermostats to HVAC maintenance and smart home upgrades, with practical thresholds for when a professional tune-up pays for itself.",
    tags: ["Energy Efficiency", "HVAC", "Home Improvement", "Montreal", "Smart Home", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 14,
    title: "Arrêtez de grimacer devant votre facture d'énergie: 10 façons de rester au chaud à moindre coût",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1158,
    readTime: 6,
    url: "https://auraclimatpro.com/arretez-de-grimacer-devant-votre-facture-denergie-10-facons-de-rester-au-chaud-a-moindre-cout/",
    excerpt: "Dix stratégies pratiques pour réduire les factures de chauffage hivernal — calfeutrage des fuites, thermostats intelligents et optimisation de la ventilation — pour rester au chaud à Montréal sans sacrifier le budget.",
    tags: ["Energy Efficiency", "HVAC", "Home Improvement", "Montreal", "French", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 15,
    title: "Boiler vs. Furnace: The Best Heating Options for Historic Beacon Hill Brownstones",
    publication: "ComfiTrust",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1039,
    readTime: 5,
    url: "https://comfitrust.com/boiler-vs-furnace-the-best-heating-options-for-historic-beacon-hill-brownstones/",
    excerpt: "Beacon Hill's solid masonry brownstones make ductwork nearly impossible — this breakdown explains why boilers outperform furnaces in historic homes, how hybrid heat pump systems fit the preservation constraints, and which Mass Save rebates apply in 2026.",
    tags: ["HVAC", "Boston", "Heat Pump", "Rebates", "Mass Save", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 16,
    title: "Why January is the Best Time for a New HVAC Quote (And Why Waiting Until Spring Could Cost You)",
    publication: "Auxaire",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1331,
    readTime: 7,
    url: "https://auxaire.com/2026/01/23/why-january-is-the-best-time-for-a-new-hvac-quote-and-why-waiting-until-spring-could-cost-you/",
    excerpt: "January is the quiet before the spring rush — and that window means better pricing, faster installs, and full access to OHPA rebates before funds run dry. This guide breaks down why the refrigerant transition to R-454B and pre-season manufacturer pricing make right now the best time to get an HVAC quote in the Maritimes.",
    tags: ["HVAC", "Rebates", "Nova Scotia", "Heat Pump", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 17,
    title: "Understanding the \"Code Error\" Flashing on Your Furnace: A Homeowner's Guide to Decoding the Blink",
    publication: "WiserAire",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1473,
    readTime: 7,
    url: "https://wiseraire.com/understanding-the-code-error-flashing-on-your-furnace-a-homeowners-guide-to-decoding-the-blink/",
    excerpt: "That blinking light on your furnace isn't random — it's a diagnostic code pointing to a specific fault like a blocked exhaust vent, high limit switch trip, or ignition failure. This Winnipeg homeowner's guide decodes the most common blink patterns and tells you which ones need a tech immediately.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Winnipeg", "Safety", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 18,
    title: "Furnace vs. Heat Pump: Which Is Better for Canadian Winters?",
    publication: "AuraClimatpro",
    date: "January 28, 2026",
    dateISO: "2026-01-28",
    wordCount: 1063,
    readTime: 5,
    url: "https://auraclimatpro.com/furnace-vs-heat-pump-which-is-better-for-canadian-winters/",
    excerpt: "Modern cold-climate heat pumps have made the furnace vs. heat pump debate more nuanced than ever. This guide explains why dual-energy systems — pairing an electric heat pump with a gas furnace backup — are the smart choice for Quebec homeowners looking to leverage low hydro rates without sacrificing winter comfort.",
    tags: ["HVAC", "Heat Pump", "Furnace", "Montreal", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 19,
    title: "Fournaise vs Thermopompe: Quel est le meilleur choix pour l'hiver québécois?",
    publication: "AuraClimatpro",
    date: "January 28, 2026",
    dateISO: "2026-01-28",
    wordCount: 1178,
    readTime: 6,
    url: "https://auraclimatpro.com/fournaise-vs-thermopompe-quel-est-le-meilleur-choix-pour-lhiver-quebecois/",
    excerpt: "La technologie moderne des thermopompes pour climat froid a changé la donne — cet article compare fournaise et thermopompe pour les hivers québécois et explique pourquoi les systèmes biénergie, combinant les deux, permettent de profiter des bas tarifs d'Hydro-Québec sans compromettre le confort.",
    tags: ["HVAC", "Heat Pump", "Furnace", "Montreal", "French", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 20,
    title: "When Should You Replace Your Furnace? 5 Clear Warning Signs",
    publication: "AuraClimatpro",
    date: "February 2, 2026",
    dateISO: "2026-02-02",
    wordCount: 1150,
    readTime: 6,
    url: "https://auraclimatpro.com/when-should-you-replace-your-furnace-5-clear-warning-signs/",
    excerpt: "Five clear signs your furnace needs replacing — age over 15 years, rising utility bills, unusual noises, uneven heating, and frequent repairs — with Montreal-specific guidance on professional installation, heritage home considerations, and how 2026 rebates make upgrading more affordable than ever.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 21,
    title: "Quand devriez-vous remplacer votre fournaise? 5 signes qui ne trompent pas",
    publication: "AuraClimatpro",
    date: "January 30, 2026",
    dateISO: "2026-01-30",
    wordCount: 1150,
    readTime: 6,
    url: "https://auraclimatpro.com/quand-devriez-vous-remplacer-votre-fournaise-5-signes-qui-ne-trompent-pas/",
    excerpt: "Votre fournaise envoie souvent des signaux d'alarme bien avant de lâcher — âge de 15 ans et plus, factures en hausse inexpliquée, bruits inhabituels, chaleur inégale, et réparations répétées sont les cinq signes qui indiquent qu'un remplacement est plus économique qu'une réparation. Guide montréalais avec conseils d'installation professionnelle.",
    tags: ["HVAC", "Furnace", "Montreal", "French", "Troubleshooting", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 22,
    title: "The Hidden Threat: Why Your Boston Home Needs a Winter Furnace Check-up Right Now",
    publication: "ComfiTrust",
    date: "February 3, 2026",
    dateISO: "2026-02-03",
    wordCount: 1100,
    readTime: 6,
    url: "https://comfitrust.com/the-hidden-threat-why-your-boston-home-needs-a-winter-furnace-check-up-right-now/",
    excerpt: "Carbon monoxide is undetectable by human senses and mimics flu symptoms — making winter the most dangerous season for Boston homeowners with aging furnaces. This guide covers snow-blocked vents, heat exchanger cracks, Massachusetts Nicole's Law detector requirements, and why a professional combustion analysis beats relying on alarms alone.",
    tags: ["HVAC", "Furnace", "Safety", "Boston", "Carbon Monoxide", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 23,
    title: "The Manitoba Hydro Home Energy Efficiency Loan: A Step-by-Step Guide",
    publication: "WiserAire",
    date: "February 4, 2026",
    dateISO: "2026-02-04",
    wordCount: 1050,
    readTime: 5,
    url: "https://wiseraire.com/the-manitoba-hydro-home-energy-efficiency-loan-a-step-by-step-guide/",
    excerpt: "Manitoba Hydro's 2026 energy efficiency loan offers up to $12,500 (or $20,000 for solar/geothermal) at a fixed 6.20% rate with no down payment — this step-by-step guide covers qualifying upgrades, the five-step application sequence, and the most common denial reasons to avoid.",
    tags: ["HVAC", "Rebates", "Manitoba", "Energy Efficiency", "Furnace", "Heat Pump"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 24,
    title: "Battery Storage Systems: Backup Power and Energy Savings for BC Homes",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-01",
    wordCount: 1200,
    readTime: 6,
    url: "https://aireenergy.com/battery-storage-systems-backup-power-and-energy-savings-for-bc-homes/",
    excerpt: "BC's aging grid and severe weather events are driving demand for home battery storage — this guide covers time-of-use rate optimization with BC Hydro's new pricing structure, LFP battery technology, stacking $10,000+ in solar and storage rebates before the April 2026 deadline, and how to integrate batteries with heat pumps and EV chargers.",
    tags: ["Energy Efficiency", "Solar", "Battery Storage", "British Columbia", "Rebates", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 25,
    title: "Le frisson de 2h du matin: que faire lors d'une urgence de chauffage en plein hiver?",
    publication: "AuraClimatpro",
    date: "February 6, 2026",
    dateISO: "2026-02-06",
    wordCount: 950,
    readTime: 5,
    url: "https://auraclimatpro.com/le-frisson-de-2h-du-matin-que-faire-lors-dune-urgence-de-chauffage-en-plein-hiver/",
    excerpt: "Quand la fournaise lâche à -20°C à 2h du matin, chaque minute compte — ce guide d'urgence couvre la checklist de base, l'inspection des filtres et des conduits PVC, les mesures anti-gel pour les tuyaux, et les trois signaux (gaz, CO, fumée) qui exigent une évacuation immédiate.",
    tags: ["HVAC", "Furnace", "Emergency", "Montreal", "French", "Safety", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 26,
    title: "The 2 AM Chill: What to Do During a Mid-Winter Heating Emergency",
    publication: "AuraClimatpro",
    date: "February 9, 2026",
    dateISO: "2026-02-09",
    wordCount: 900,
    readTime: 5,
    url: "https://auraclimatpro.com/the-2-am-chill-what-to-do-during-a-mid-winter-heating-emergency/",
    excerpt: "When your furnace dies at -20°C in the middle of the night, every minute counts — this emergency guide walks through the quick-check checklist, airflow fixes, pipe-freeze prevention, and the three warning signs (gas, CO, burning smell) that mean you need to evacuate immediately.",
    tags: ["HVAC", "Furnace", "Emergency", "Montreal", "Safety", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--mint))"
  },
  {
    id: 27,
    title: "Heating Your Home with Oil? Switch to an Electric Heat Pump at No Cost",
    publication: "ConstantHomeComfort",
    date: "February 9, 2026",
    dateISO: "2026-02-09",
    wordCount: 150,
    readTime: 1,
    url: "https://constanthomecomfort.com/heating-your-home-with-oil-switch-to-an-electric-heat-pump-at-no-cost/",
    excerpt: "Ontario's Oil to Heat Pump Affordability Program — funded by NRCan and the IESO — offers eligible oil-heated homeowners a free electric heat pump installation. Constant Home Comfort is an approved CLEAResult referral contractor for the program.",
    tags: ["Heat Pump", "Rebates", "Energy Efficiency", "Ontario", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 28,
    title: "The Winter Trap: Why Your Indoor Air Quality Drops When the Temperature Plummets",
    publication: "ComfiTrust",
    date: "February 10, 2026",
    dateISO: "2026-02-10",
    wordCount: 1800,
    readTime: 9,
    url: "https://comfitrust.com/the-winter-trap-why-your-indoor-air-quality-drops-when-the-temperature-plummets/",
    excerpt: "Indoor air can be up to five times more polluted than outdoor air in winter — sealed homes, furnace dust, low humidity, and cooking particulates all compound the problem. This Boston-focused guide covers True HEPA filtration, UV-C light purification, and the 30-50% humidity \"Goldilocks Zone\" for healthier winter air.",
    tags: ["HVAC", "Air Quality", "Boston", "Health", "Furnace", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 29,
    title: "Furnace End-of-Life: Repair or Replace? (The $500 Rule)",
    publication: "WiserAire",
    date: "February 11, 2026",
    dateISO: "2026-02-11",
    wordCount: 1100,
    readTime: 6,
    url: "https://wiseraire.com/furnace-end-of-life-repair-or-replace-the-500-rule/",
    excerpt: "Three rules help Winnipeg homeowners decide between furnace repair and replacement: the $500 Rule for minor fixes, the 5000 HVAC Rule (age × repair cost), and the 50% Rule when quotes approach half the cost of a new system — plus why a cracked heat exchanger almost always tips the math toward replacement.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Winnipeg", "Home Improvement", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 30,
    title: "Turning the Vancouver Rain into ROI: Your Guide to BC Solar in 2026",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-01",
    wordCount: 1800,
    readTime: 9,
    url: "https://aireenergy.com/turning-the-vancouver-rain-into-roi-your-guide-to-bc-solar-in-2026/",
    excerpt: "Vancouver's cloudy reputation undersells its solar potential — modern PERC panels capture diffuse light effectively, and BC's 2026 rebates stack up to $10,000 before April 1st changes hit. This guide covers net metering credits, battery integration, optimal roof angles for rain self-cleaning, and financial projections showing break-even in 8–12 years.",
    tags: ["Solar", "Energy Efficiency", "British Columbia", "Rebates", "Battery Storage", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 31,
    title: "Furnace End-of-Life: Repair or Replace? (The $500 Rule)",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-15",
    wordCount: 1100,
    readTime: 6,
    url: "https://aireenergy.com/furnace-end-of-life-repair-or-replace-the-500-rule/",
    excerpt: "Vancouver homeowners weighing furnace repair vs. replacement can use three simple rules — the $500 threshold for minor fixes, the 5000 HVAC Rule (age × repair cost), and the 50% Rule — to cut through the pressure of a mid-winter breakdown. Cracked heat exchangers are the one exception that almost always mandate full replacement regardless of cost.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "British Columbia", "Home Improvement", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 32,
    title: "Votre maison étouffe-t-elle? Pourquoi la qualité de l'air est vitale cet hiver au Québec",
    publication: "AuraClimatpro",
    date: "February 18, 2026",
    dateISO: "2026-02-18",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/votre-maison-etouffe-t-elle-pourquoi-la-qualite-de-lair-est-vitale-cet-hiver-au-quebec/",
    excerpt: "Les maisons québécoises hermétiquement fermées en hiver piègent des polluants 2 à 5 fois plus concentrés qu'à l'extérieur — poussières, COV, particules virales et radon. Ce guide couvre la gestion de l'humidité (30–50%), la technologie Lennox PureAir S, et les ventilateurs à récupération de chaleur (VRC) pour respirer sainement sans gaspiller l'énergie.",
    tags: ["HVAC", "Air Quality", "Montreal", "French", "Health", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 33,
    title: "Your Home is Holding Its Breath: Why Winter Air Quality is a Health Priority",
    publication: "AuraClimatpro",
    date: "February 18, 2026",
    dateISO: "2026-02-18",
    wordCount: 1400,
    readTime: 7,
    url: "https://auraclimatpro.com/your-home-is-holding-its-breath-why-winter-air-quality-is-a-health-priority/",
    excerpt: "Sealed winter homes trap indoor air that's 2–5× more polluted than outside — accumulating dust, VOCs, airborne pathogens, and radon. This Montreal guide covers whole-home humidification (targeting 30–50%), the Lennox PureAir S system's three-layer purification, and HRV/ERV ventilation for fresh air without heat loss.",
    tags: ["HVAC", "Air Quality", "Montreal", "Health", "Winter", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 34,
    title: "À quelle fréquence devriez-vous faire l'entretien de votre fournaise? Le guide complet pour un hiver sans tracas",
    publication: "AuraClimatpro",
    date: "February 24, 2026",
    dateISO: "2026-02-24",
    wordCount: 1800,
    readTime: 9,
    url: "https://auraclimatpro.com/a-quelle-frequence-devriez-vous-faire-lentretien-de-votre-fournaise-le-guide-complet-pour-un-hiver-sans-tracas/",
    excerpt: "Les fournaises québécoises tournent 2 000 à 3 000 heures par hiver — un entretien annuel en septembre-octobre protège la garantie, évite 15% de surconsommation énergétique et détecte les fuites de monoxyde de carbone avant le grand froid. Guide complet des tâches DIY, des inspections professionnelles et des signaux d'alarme à surveiller.",
    tags: ["HVAC", "Furnace", "Montreal", "French", "Home Improvement", "Safety"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 35,
    title: "How Often Should You Service Your Furnace? A Complete Guide to Heating Reliability",
    publication: "AuraClimatpro",
    date: "February 24, 2026",
    dateISO: "2026-02-24",
    wordCount: 1300,
    readTime: 7,
    url: "https://auraclimatpro.com/how-often-should-you-service-your-furnace-a-complete-guide-to-heating-reliability/",
    excerpt: "Annual furnace servicing in late September or October protects your warranty, catches carbon monoxide risks early, and can cut energy bills — this guide draws the line between what Montreal homeowners can handle themselves (filter checks, vent clearing) and what needs a technician (combustion calibration, burner cleaning, electrical inspection).",
    tags: ["HVAC", "Furnace", "Montreal", "Home Improvement", "Safety", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 36,
    title: "Ductless Mini-Splits: Are They Really the Right Move for Your Home?",
    publication: "AuraClimatpro",
    date: "March 2, 2026",
    dateISO: "2026-03-02",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/ductless-mini-splits-are-they-really-the-right-move-for-your-home/",
    excerpt: "Ductless mini-split systems promise zoned comfort and significant energy savings — but are they the right fit for Canadian homes? This guide examines cold-climate performance, installation costs, Quebec and Ontario rebate eligibility, and how mini-splits stack up against traditional central systems for Ottawa and Gatineau homeowners.",
    tags: ["HVAC", "Heat Pump", "Mini-Split", "Energy Efficiency", "Ottawa", "Rebates", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--mint))"
  },
  {
    id: 37,
    title: "Mini-splits sans conduits: Est-ce vraiment la solution idéale pour votre foyer?",
    publication: "AuraClimatpro",
    date: "March 2, 2026",
    dateISO: "2026-03-02",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/mini-splits-sans-conduits-est-ce-vraiment-la-solution-ideale-pour-votre-foyer/",
    excerpt: "Les systèmes mini-split sans conduits promettent confort par zone et économies d'énergie — mais sont-ils le bon choix pour les maisons canadiennes? Ce guide examine les performances en climat froid, les coûts d'installation, l'admissibilité aux subventions du Québec et de l'Ontario, et la comparaison avec les systèmes centraux traditionnels pour les propriétaires d'Ottawa-Gatineau.",
    tags: ["HVAC", "Thermopompe", "Mini-Split", "Efficacité Énergétique", "Ottawa", "Subventions", "French"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 38,
    title: "Strategic Content Whitepaper: Optimizing Winter HVAC Assets for Aura ClimatPro",
    publication: "AuraClimatpro",
    date: "March 4, 2026",
    dateISO: "2026-03-04",
    wordCount: 1200,
    readTime: 6,
    url: "https://auraclimatpro.com/strategic-content-whitepaper-optimizing-winter-hvac-assets-for-aura-climatpro/",
    excerpt: "A comprehensive guide to winter heat pump maintenance and operation for Quebec homeowners — debunking cold-weather performance myths and providing practical strategies for filter care, snow clearance, defrost cycle management, and thermostat optimization to keep systems running efficiently through the harshest months.",
    tags: ["HVAC", "Heat Pump", "Winter", "Montreal", "Maintenance", "Energy Efficiency", "Quebec"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 39,
    title: "Livre blanc sur le contenu stratégique : Optimisation des actifs CVC hivernaux pour Aura ClimatPro",
    publication: "AuraClimatpro",
    date: "March 4, 2026",
    dateISO: "2026-03-04",
    wordCount: 1800,
    readTime: 9,
    url: "https://auraclimatpro.com/livre-blanc-sur-le-contenu-strategique-optimisation-des-actifs-cvc-hivernaux-pour-aura-climatpro/",
    excerpt: "Comment optimiser les systèmes de thermopompes pendant l'hiver québécois — démystifiant les mythes courants sur les performances par temps froid et fournissant des directives pratiques d'entretien pour les filtres, le dégagement de neige, les cycles de dégivrage et l'optimisation du thermostat pour une efficacité maximale toute la saison.",
    tags: ["HVAC", "Thermopompe", "Hiver", "Montreal", "Entretien", "Efficacité Énergétique", "French"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 40,
    title: "Preventing Ice Damming: Is Your Attic Ventilation Working?",
    publication: "Auxaire",
    date: "March 5, 2026",
    dateISO: "2026-03-05",
    wordCount: 1800,
    readTime: 9,
    url: "https://auxaire.com/2026/03/05/preventing-ice-damming-is-your-attic-ventilation-working/",
    excerpt: "Ice dams aren't just a winter nuisance — they're a sign of thermal failure in your attic. This guide explains how freeze-thaw cycles in Maritime climates drive ice dam formation, what proper intake and exhaust ventilation should look like, and how Nova Scotia, New Brunswick, and PEI rebate programs can offset the cost of fixing it.",
    tags: ["HVAC", "Insulation", "Attic", "Nova Scotia", "Winter", "Rebates", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 41,
    title: "The Early Bird Special: Why March is the Smartest Month for a Boston AC Tune-Up",
    publication: "ComfiTrust",
    date: "March 5, 2026",
    dateISO: "2026-03-05",
    wordCount: 1200,
    readTime: 6,
    url: "https://comfitrust.com/the-early-bird-special-why-march-is-the-smartest-month-for-a-boston-ac-tune-up/",
    excerpt: "Scheduling AC maintenance in March — before the summer rush hits — means shorter waits, better rebate availability, and catching winter dormancy damage before it compounds. This piece covers 2026 Mass Save changes, the R-410A phase-out, and why Boston's triple-deckers and brownstones need region-specific cooling strategies.",
    tags: ["HVAC", "Air Conditioning", "Boston", "Rebates", "Mass Save", "Heat Pump", "Spring"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 42,
    title: "5 Mistakes to Avoid When Choosing a New AC Unit in Boston: Sizing, SEER2, and Rebate Traps",
    publication: "ComfiTrust",
    date: "March 17, 2026",
    dateISO: "2026-03-17",
    wordCount: 1800,
    readTime: 9,
    url: "https://comfitrust.com/5-mistakes-to-avoid-when-choosing-a-new-ac-unit-in-boston-sizing-seer2-and-rebate-traps/",
    excerpt: "Oversizing, ignoring SEER2 minimums, skipping ductwork assessment, missing the R-410A phase-out, and falling into Mass Save rebate traps — five costly mistakes Boston homeowners make when buying a new AC unit. This guide walks through each one with the Manual J and Manual D math that actually matters.",
    tags: ["HVAC", "Air Conditioning", "Boston", "Mass Save", "Rebates", "Energy Efficiency", "Buying Guide"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 43,
    title: "Supporting Local: Why Choosing a Boston-Based HVAC Firm Matters",
    publication: "ComfiTrust",
    date: "March 17, 2026",
    dateISO: "2026-03-17",
    wordCount: 1200,
    readTime: 6,
    url: "https://comfitrust.com/supporting-local-why-choosing-a-boston-based-hvac-firm-matters/",
    excerpt: "Local Boston HVAC contractors bring more than just proximity — they bring knowledge of historic district compliance, coastal corrosion challenges, and 2026 Mass Save rebate navigation that national chains simply don't have. Every $100 spent locally recirculates $50 back into Greater Boston, versus $15 with a national chain.",
    tags: ["HVAC", "Boston", "Mass Save", "Heat Pump", "Local Business", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  }
];
