const BLOGS = [
  {
    id: 1,
    title: "Technoeconomic Analysis: The 2026 Shift to Smart HVAC Standards in Greater Boston",
    publication: "ComfiTrust",
    date: "January 5, 2026",
    dateISO: "2026-01-05",
    wordCount: 1320,
    readTime: 7,
    url: "https://comfitrust.com/technoeconomic-analysis-the-2026-shift-to-smart-hvac-standards-in-greater-boston/",
    excerpt: "As of 2026, Boston's HVAC sector has crossed the tipping point where system intelligence replaces mechanical reliability as the primary quality metric — driven by BERDO emissions mandates, R-410A refrigerant phase-outs, and AI-powered predictive comfort systems reshaping how Greater Boston homes manage climate and energy.",
    tags: ["HVAC", "Smart Home", "Energy Efficiency", "Boston", "AI", "Real Estate"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 2,
    title: "The Emergency 'No-Heat' Playbook: What to Do During a Polar Vortex",
    publication: "ComfiTrust",
    date: "January 8, 2026",
    dateISO: "2026-01-08",
    wordCount: 973,
    readTime: 5,
    url: "https://comfitrust.com/the-emergency-no-heat-playbook-what-to-do-during-a-polar-vortex/",
    excerpt: "When a Polar Vortex hits Greater Boston, it's a brutal test of your home's high-efficiency heating system. This step-by-step emergency playbook covers safety triage, PVC vent checks, error code decoding for Gree, Mitsubishi, and Bosch systems, and how to protect your pipes — so you're never left in the cold at 2 AM.",
    tags: ["HVAC", "Emergency", "Heat Pump", "Boston", "Winter", "Troubleshooting"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 3,
    title: "Massachusetts Heat Pump Reality Check: Do They Really Work at -15°F?",
    publication: "ComfiTrust",
    date: "January 12, 2026",
    dateISO: "2026-01-12",
    wordCount: 1034,
    readTime: 5,
    url: "https://comfitrust.com/massachusetts-heat-pump-reality-check-do-they-really-work-at-15f/",
    excerpt: "A technical reality check on air-source heat pumps in New England winters — examining COP ratings across temperature ranges, EVI and Flash Injection technology, brand comparisons across Mitsubishi, Bosch, and Daikin, and Massachusetts-specific rebates and the No-Cost Heat Pump Program.",
    tags: ["HVAC", "Heat Pump", "Massachusetts", "Winter", "Rebates", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 4,
    title: "Nova Scotia Rebate Update: The 2026 Guide",
    publication: "Auxaire",
    date: "January 13, 2026",
    dateISO: "2026-01-13",
    wordCount: 1573,
    readTime: 8,
    url: "https://auxaire.com/2026/01/13/nova-scotia-rebate-update-the-2026-guide/",
    excerpt: "Nova Scotia homeowners can stack up to $30,000 in 2026 rebates for switching from oil to heat pumps — but major programs are expected to deplete early. This guide covers OHPA grants, income-based top-ups, Efficiency NS home assessments, supplemental insulation rebates, and 0% PACE financing options.",
    tags: ["Rebates", "Nova Scotia", "Heat Pump", "Energy Efficiency", "HVAC", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 5,
    title: "The \"Burning Plastic\" Smell: Is Your Furnace Safe?",
    publication: "WiserAire",
    date: "January 14, 2026",
    dateISO: "2026-01-14",
    wordCount: 1566,
    readTime: 8,
    url: "https://wiseraire.com/the-burning-plastic-smell-is-your-furnace-safe/",
    excerpt: "That burning plastic smell from your furnace could be dust — or a failing blower motor, electrical arcing, or a cracked heat exchanger leaking carbon monoxide. This Winnipeg-focused guide walks through the three main causes, emergency shutdown steps, and when to call for 24/7 repair.",
    tags: ["HVAC", "Furnace", "Safety", "Winnipeg", "Carbon Monoxide", "Troubleshooting"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 6,
    title: "Is Your Heat Pump Ready for -30°C? A Maritime Survival Guide",
    publication: "Auxaire",
    date: "January 9, 2026",
    dateISO: "2026-01-09",
    wordCount: 1346,
    readTime: 7,
    url: "https://auxaire.com/2026/01/09/is-your-heat-pump-ready-for-30c-a-maritime-survival-guide/",
    excerpt: "Modern cold-climate heat pumps can hold the line at -30°C — but only if they're properly sized, coated for coastal salt air, and backed by the right dual-fuel strategy. This Maritime survival guide covers Enhanced Vapor Injection technology, anti-corrosion coatings, frost management, and 2026 rebate programs offering up to $30,000 in Nova Scotia.",
    tags: ["HVAC", "Heat Pump", "Nova Scotia", "Winter", "Rebates", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 7,
    title: "Navigating the 2026 Mass Save Rebate Reductions: What You Need to Know NOW",
    publication: "ComfiTrust",
    date: "January 15, 2026",
    dateISO: "2026-01-15",
    wordCount: 1515,
    readTime: 8,
    url: "https://comfitrust.com/navigating-the-2026-mass-save-rebate-reductions-what-you-need-to-know-now/",
    excerpt: "Massachusetts homeowners face a \"triple hit\" to heat pump budgets in 2026 as Mass Save slashes maximum rebates from $10,000 to $8,500, new tonnage-based calculations and refrigerant compliance rules tighten eligibility, and federal Section 25C tax credits expire — with a breakdown of what to do before the cuts take full effect.",
    tags: ["HVAC", "Heat Pump", "Massachusetts", "Rebates", "Energy Efficiency", "Mass Save"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 8,
    title: "Manitoba Hydro Bills Too High? 5 Ways to Optimize Your Furnace Today",
    publication: "WiserAire",
    date: "January 16, 2026",
    dateISO: "2026-01-16",
    wordCount: 1761,
    readTime: 9,
    url: "https://wiseraire.com/manitoba-hydro-bills-too-high-5-ways-to-optimize-your-furnace-today/",
    excerpt: "Five practical strategies for cutting Manitoba Hydro bills through furnace optimization — from filter swaps and duct sealing to smart thermostats and intelligent monitoring — with cost estimates and expected savings for each upgrade.",
    tags: ["HVAC", "Furnace", "Energy Efficiency", "Winnipeg", "Manitoba", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 9,
    title: "Why Your Boston Home Has Hot and Cold Spots (and How to Fix Them)",
    publication: "ComfiTrust",
    date: "January 20, 2026",
    dateISO: "2026-01-20",
    wordCount: 1436,
    readTime: 7,
    url: "https://comfitrust.com/why-your-boston-home-has-hot-and-cold-spots-and-how-to-fix-them/",
    excerpt: "Boston homes battle temperature imbalances caused by the stack effect, aging ductwork, and urban heat islands — this guide covers professional air balancing, zoning systems, and ductless mini-splits as targeted fixes, with Mass Save rebates that can offset upgrade costs.",
    tags: ["HVAC", "Boston", "Heat Pump", "Energy Efficiency", "Mass Save", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 10,
    title: "Where Should You Actually Put CO Detectors in a Split-Level Home?",
    publication: "WiserAire",
    date: "January 22, 2026",
    dateISO: "2026-01-22",
    wordCount: 1036,
    readTime: 5,
    url: "https://wiseraire.com/where-should-you-actually-put-co-detectors-in-a-split-level-home/",
    excerpt: "CO doesn't sink or rise — it follows airflow, which makes split-level homes especially tricky. This guide covers the exact placement rules for bedroom doors, garage entries, and mechanical spaces, plus the common installation mistakes that leave dangerous blind spots.",
    tags: ["Safety", "Carbon Monoxide", "HVAC", "Furnace", "Winnipeg", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 11,
    title: "Why Is My Furnace Blowing Cold Air?",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1197,
    readTime: 6,
    url: "https://auraclimatpro.com/why-is-my-furnace-blowing-cold-air/",
    excerpt: "A furnace blowing cold air isn't always a crisis — seven common culprits from thermostat mode to dirty filters can be ruled out before calling a tech. This Montreal-focused guide walks through each cause and the DIY fix or escalation threshold for each.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--lavender))"
  },
  {
    id: 12,
    title: "Pourquoi mon fournaise souffle-t-elle de l'air froid?",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1415,
    readTime: 7,
    url: "https://auraclimatpro.com/pourquoi-mon-fournaise-souffle-t-elle-de-lair-froid/",
    excerpt: "Une fournaise qui souffle de l'air froid n'est pas toujours en panne — sept causes courantes, du réglage du thermostat au filtre encrassé, peuvent être éliminées avant d'appeler un technicien. Guide de dépannage pour propriétaires montréalais.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "French", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 13,
    title: "Stop Cringing at Your Energy Bill: 10 Ways to Stay Warm for Less",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1022,
    readTime: 5,
    url: "https://auraclimatpro.com/stop-cringing-at-your-energy-bill-10-ways-to-stay-warm-for-less/",
    excerpt: "Ten budget-friendly strategies to cut winter heating costs without sacrificing comfort — from weatherstripping and programmable thermostats to HVAC maintenance and smart home upgrades, with practical thresholds for when a professional tune-up pays for itself.",
    tags: ["Energy Efficiency", "HVAC", "Home Improvement", "Montreal", "Smart Home", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 14,
    title: "Arrêtez de grimacer devant votre facture d'énergie: 10 façons de rester au chaud à moindre coût",
    publication: "AuraClimatpro",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1158,
    readTime: 6,
    url: "https://auraclimatpro.com/arretez-de-grimacer-devant-votre-facture-denergie-10-facons-de-rester-au-chaud-a-moindre-cout/",
    excerpt: "Dix stratégies pratiques pour réduire les factures de chauffage hivernal — calfeutrage des fuites, thermostats intelligents et optimisation de la ventilation — pour rester au chaud à Montréal sans sacrifier le budget.",
    tags: ["Energy Efficiency", "HVAC", "Home Improvement", "Montreal", "French", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--pink))"
  },
  {
    id: 15,
    title: "Boiler vs. Furnace: The Best Heating Options for Historic Beacon Hill Brownstones",
    publication: "ComfiTrust",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1039,
    readTime: 5,
    url: "https://comfitrust.com/boiler-vs-furnace-the-best-heating-options-for-historic-beacon-hill-brownstones/",
    excerpt: "Beacon Hill's solid masonry brownstones make ductwork nearly impossible — this breakdown explains why boilers outperform furnaces in historic homes, how hybrid heat pump systems fit the preservation constraints, and which Mass Save rebates apply in 2026.",
    tags: ["HVAC", "Boston", "Heat Pump", "Rebates", "Mass Save", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 16,
    title: "Why January is the Best Time for a New HVAC Quote (And Why Waiting Until Spring Could Cost You)",
    publication: "Auxaire",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1331,
    readTime: 7,
    url: "https://auxaire.com/2026/01/23/why-january-is-the-best-time-for-a-new-hvac-quote-and-why-waiting-until-spring-could-cost-you/",
    excerpt: "January is the quiet before the spring rush — and that window means better pricing, faster installs, and full access to OHPA rebates before funds run dry. This guide breaks down why the refrigerant transition to R-454B and pre-season manufacturer pricing make right now the best time to get an HVAC quote in the Maritimes.",
    tags: ["HVAC", "Rebates", "Nova Scotia", "Heat Pump", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 17,
    title: "Understanding the \"Code Error\" Flashing on Your Furnace: A Homeowner's Guide to Decoding the Blink",
    publication: "WiserAire",
    date: "January 23, 2026",
    dateISO: "2026-01-23",
    wordCount: 1473,
    readTime: 7,
    url: "https://wiseraire.com/understanding-the-code-error-flashing-on-your-furnace-a-homeowners-guide-to-decoding-the-blink/",
    excerpt: "That blinking light on your furnace isn't random — it's a diagnostic code pointing to a specific fault like a blocked exhaust vent, high limit switch trip, or ignition failure. This Winnipeg homeowner's guide decodes the most common blink patterns and tells you which ones need a tech immediately.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Winnipeg", "Safety", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 18,
    title: "Furnace vs. Heat Pump: Which Is Better for Canadian Winters?",
    publication: "AuraClimatpro",
    date: "January 28, 2026",
    dateISO: "2026-01-28",
    wordCount: 1063,
    readTime: 5,
    url: "https://auraclimatpro.com/furnace-vs-heat-pump-which-is-better-for-canadian-winters/",
    excerpt: "Modern cold-climate heat pumps have made the furnace vs. heat pump debate more nuanced than ever. This guide explains why dual-energy systems — pairing an electric heat pump with a gas furnace backup — are the smart choice for Quebec homeowners looking to leverage low hydro rates without sacrificing winter comfort.",
    tags: ["HVAC", "Heat Pump", "Furnace", "Montreal", "Energy Efficiency", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 19,
    title: "Fournaise vs Thermopompe: Quel est le meilleur choix pour l'hiver québécois?",
    publication: "AuraClimatpro",
    date: "January 28, 2026",
    dateISO: "2026-01-28",
    wordCount: 1178,
    readTime: 6,
    url: "https://auraclimatpro.com/fournaise-vs-thermopompe-quel-est-le-meilleur-choix-pour-lhiver-quebecois/",
    excerpt: "La technologie moderne des thermopompes pour climat froid a changé la donne — cet article compare fournaise et thermopompe pour les hivers québécois et explique pourquoi les systèmes biénergie, combinant les deux, permettent de profiter des bas tarifs d'Hydro-Québec sans compromettre le confort.",
    tags: ["HVAC", "Heat Pump", "Furnace", "Montreal", "French", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 20,
    title: "When Should You Replace Your Furnace? 5 Clear Warning Signs",
    publication: "AuraClimatpro",
    date: "February 2, 2026",
    dateISO: "2026-02-02",
    wordCount: 1150,
    readTime: 6,
    url: "https://auraclimatpro.com/when-should-you-replace-your-furnace-5-clear-warning-signs/",
    excerpt: "Five clear signs your furnace needs replacing — age over 15 years, rising utility bills, unusual noises, uneven heating, and frequent repairs — with Montreal-specific guidance on professional installation, heritage home considerations, and how 2026 rebates make upgrading more affordable than ever.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Montreal", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--lavender))"
  },
  {
    id: 21,
    title: "Quand devriez-vous remplacer votre fournaise? 5 signes qui ne trompent pas",
    publication: "AuraClimatpro",
    date: "January 30, 2026",
    dateISO: "2026-01-30",
    wordCount: 1150,
    readTime: 6,
    url: "https://auraclimatpro.com/quand-devriez-vous-remplacer-votre-fournaise-5-signes-qui-ne-trompent-pas/",
    excerpt: "Votre fournaise envoie souvent des signaux d'alarme bien avant de lâcher — âge de 15 ans et plus, factures en hausse inexpliquée, bruits inhabituels, chaleur inégale, et réparations répétées sont les cinq signes qui indiquent qu'un remplacement est plus économique qu'une réparation. Guide montréalais avec conseils d'installation professionnelle.",
    tags: ["HVAC", "Furnace", "Montreal", "French", "Troubleshooting", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--peach))"
  },
  {
    id: 22,
    title: "The Hidden Threat: Why Your Boston Home Needs a Winter Furnace Check-up Right Now",
    publication: "ComfiTrust",
    date: "February 3, 2026",
    dateISO: "2026-02-03",
    wordCount: 1100,
    readTime: 6,
    url: "https://comfitrust.com/the-hidden-threat-why-your-boston-home-needs-a-winter-furnace-check-up-right-now/",
    excerpt: "Carbon monoxide is undetectable by human senses and mimics flu symptoms — making winter the most dangerous season for Boston homeowners with aging furnaces. This guide covers snow-blocked vents, heat exchanger cracks, Massachusetts Nicole's Law detector requirements, and why a professional combustion analysis beats relying on alarms alone.",
    tags: ["HVAC", "Furnace", "Safety", "Boston", "Carbon Monoxide", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 23,
    title: "The Manitoba Hydro Home Energy Efficiency Loan: A Step-by-Step Guide",
    publication: "WiserAire",
    date: "February 4, 2026",
    dateISO: "2026-02-04",
    wordCount: 1050,
    readTime: 5,
    url: "https://wiseraire.com/the-manitoba-hydro-home-energy-efficiency-loan-a-step-by-step-guide/",
    excerpt: "Manitoba Hydro's 2026 energy efficiency loan offers up to $12,500 (or $20,000 for solar/geothermal) at a fixed 6.20% rate with no down payment — this step-by-step guide covers qualifying upgrades, the five-step application sequence, and the most common denial reasons to avoid.",
    tags: ["HVAC", "Rebates", "Manitoba", "Energy Efficiency", "Furnace", "Heat Pump"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--pink))"
  },
  {
    id: 24,
    title: "Battery Storage Systems: Backup Power and Energy Savings for BC Homes",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-01",
    wordCount: 1200,
    readTime: 6,
    url: "https://aireenergy.com/battery-storage-systems-backup-power-and-energy-savings-for-bc-homes/",
    excerpt: "BC's aging grid and severe weather events are driving demand for home battery storage — this guide covers time-of-use rate optimization with BC Hydro's new pricing structure, LFP battery technology, stacking $10,000+ in solar and storage rebates before the April 2026 deadline, and how to integrate batteries with heat pumps and EV chargers.",
    tags: ["Energy Efficiency", "Solar", "Battery Storage", "British Columbia", "Rebates", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--peach))"
  },
  {
    id: 25,
    title: "Le frisson de 2h du matin: que faire lors d'une urgence de chauffage en plein hiver?",
    publication: "AuraClimatpro",
    date: "February 6, 2026",
    dateISO: "2026-02-06",
    wordCount: 950,
    readTime: 5,
    url: "https://auraclimatpro.com/le-frisson-de-2h-du-matin-que-faire-lors-dune-urgence-de-chauffage-en-plein-hiver/",
    excerpt: "Quand la fournaise lâche à -20°C à 2h du matin, chaque minute compte — ce guide d'urgence couvre la checklist de base, l'inspection des filtres et des conduits PVC, les mesures anti-gel pour les tuyaux, et les trois signaux (gaz, CO, fumée) qui exigent une évacuation immédiate.",
    tags: ["HVAC", "Furnace", "Emergency", "Montreal", "French", "Safety", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  },
  {
    id: 26,
    title: "The 2 AM Chill: What to Do During a Mid-Winter Heating Emergency",
    publication: "AuraClimatpro",
    date: "February 9, 2026",
    dateISO: "2026-02-09",
    wordCount: 900,
    readTime: 5,
    url: "https://auraclimatpro.com/the-2-am-chill-what-to-do-during-a-mid-winter-heating-emergency/",
    excerpt: "When your furnace dies at -20°C in the middle of the night, every minute counts — this emergency guide walks through the quick-check checklist, airflow fixes, pipe-freeze prevention, and the three warning signs (gas, CO, burning smell) that mean you need to evacuate immediately.",
    tags: ["HVAC", "Furnace", "Emergency", "Montreal", "Safety", "Winter"],
    accentGradient: "linear-gradient(180deg, var(--pink), var(--mint))"
  },
  {
    id: 27,
    title: "Heating Your Home with Oil? Switch to an Electric Heat Pump at No Cost",
    publication: "ConstantHomeComfort",
    date: "February 9, 2026",
    dateISO: "2026-02-09",
    wordCount: 150,
    readTime: 1,
    url: "https://constanthomecomfort.com/heating-your-home-with-oil-switch-to-an-electric-heat-pump-at-no-cost/",
    excerpt: "Ontario's Oil to Heat Pump Affordability Program — funded by NRCan and the IESO — offers eligible oil-heated homeowners a free electric heat pump installation. Constant Home Comfort is an approved CLEAResult referral contractor for the program.",
    tags: ["Heat Pump", "Rebates", "Energy Efficiency", "Ontario", "Home Improvement"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--lavender))"
  },
  {
    id: 28,
    title: "The Winter Trap: Why Your Indoor Air Quality Drops When the Temperature Plummets",
    publication: "ComfiTrust",
    date: "February 10, 2026",
    dateISO: "2026-02-10",
    wordCount: 1800,
    readTime: 9,
    url: "https://comfitrust.com/the-winter-trap-why-your-indoor-air-quality-drops-when-the-temperature-plummets/",
    excerpt: "Indoor air can be up to five times more polluted than outdoor air in winter — sealed homes, furnace dust, low humidity, and cooking particulates all compound the problem. This Boston-focused guide covers True HEPA filtration, UV-C light purification, and the 30-50% humidity \"Goldilocks Zone\" for healthier winter air.",
    tags: ["HVAC", "Air Quality", "Boston", "Health", "Furnace", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--mint), var(--pink))"
  },
  {
    id: 29,
    title: "Furnace End-of-Life: Repair or Replace? (The $500 Rule)",
    publication: "WiserAire",
    date: "February 11, 2026",
    dateISO: "2026-02-11",
    wordCount: 1100,
    readTime: 6,
    url: "https://wiseraire.com/furnace-end-of-life-repair-or-replace-the-500-rule/",
    excerpt: "Three rules help Winnipeg homeowners decide between furnace repair and replacement: the $500 Rule for minor fixes, the 5000 HVAC Rule (age × repair cost), and the 50% Rule when quotes approach half the cost of a new system — plus why a cracked heat exchanger almost always tips the math toward replacement.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "Winnipeg", "Home Improvement", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--mint))"
  },
  {
    id: 30,
    title: "Turning the Vancouver Rain into ROI: Your Guide to BC Solar in 2026",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-01",
    wordCount: 1800,
    readTime: 9,
    url: "https://aireenergy.com/turning-the-vancouver-rain-into-roi-your-guide-to-bc-solar-in-2026/",
    excerpt: "Vancouver's cloudy reputation undersells its solar potential — modern PERC panels capture diffuse light effectively, and BC's 2026 rebates stack up to $10,000 before April 1st changes hit. This guide covers net metering credits, battery integration, optimal roof angles for rain self-cleaning, and financial projections showing break-even in 8–12 years.",
    tags: ["Solar", "Energy Efficiency", "British Columbia", "Rebates", "Battery Storage", "Smart Home"],
    accentGradient: "linear-gradient(180deg, var(--peach), var(--mint))"
  },
  {
    id: 31,
    title: "Furnace End-of-Life: Repair or Replace? (The $500 Rule)",
    publication: "AireEnergy",
    date: "February 2026",
    dateISO: "2026-02-01",
    wordCount: 1100,
    readTime: 6,
    url: "https://aireenergy.com/furnace-end-of-life-repair-or-replace-the-500-rule/",
    excerpt: "Three rules help Vancouver homeowners decide between furnace repair and replacement: the $500 Rule for minor fixes, the 5000 HVAC Rule (age × repair cost), and the 50% Rule when quotes approach half the cost of a new system — plus why a cracked heat exchanger almost always tips the math toward replacement.",
    tags: ["HVAC", "Furnace", "Troubleshooting", "British Columbia", "Home Improvement", "Energy Efficiency"],
    accentGradient: "linear-gradient(180deg, var(--lavender), var(--peach))"
  }
];
